### ISSUE TITLE
⌘ + d for editor.action.addSelectionToNextFindMatch does not work reliably

### ISSUE THREAD

**Issue by kentcdodds** [VSCodeVim/Vim#1024]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

In the gif here, I have this extension installed and I:
1. Navigate to where I want
2. Enter insert mode
3. Hit <kbd>cmd</kbd> + <kbd>d</kbd> multiple times which I have mapped to `editor.action.addSelectionToNextFindMatch`

In some rare (seemingly random) scenarios it actually does work as expected.

![cmdd](https://cloud.githubusercontent.com/assets/1500684/19897757/eff6b38c-a01e-11e6-983a-7b4e96a72adc.gif)

### What did you expect to happen?

In this gif, I do not have the extension installed and I do the same thing effectively, except this time it works.

![cmdd-working](https://cloud.githubusercontent.com/assets/1500684/19897761/f2e608fe-a01e-11e6-950c-a45cd1a58080.gif)

### What happened instead?

With the extension installed, the matching items are not added to the selection like they are when the plugin is not installed.

### Technical details:

* VSCode Version: 1.6.1
* VsCodeVim Version: 0.4.1
* OS: OS X El Capitan v10.11.6

**Comment by kentcdodds** [comment]
[Someone recommended](https://twitter.com/bodiddlie/status/793502214677368832) that I try [amVim](https://github.com/aioutecism/amVim-for-VSCode), so far so good...

**Comment by rebornix** [comment]
@johnfn I suppose it's another handleSelection change bug.

**Comment by johnfn** [comment]
This appears to be a recent regression.

**Comment by OliverJAsh** [comment]
Is there any known workaround for this? Unfortunately this is what is stopping me from using the extension.

**Comment by johnfn** [comment]
Sorry for taking a while there. This should be fixed on master. Let me know if there are any problems. :)

**Comment by dsifford** [comment]
Still not fixed for me. Tried in a few different locations and wasn't even able to get it work once.

amVim does work per @kentcdodds's recommendation

**Comment by johnfn** [comment]
@dsifford cmd-d should certainly work. Can you please tell me a little more about your configuration and how you are using cmd-d? 

Also, could you please try gc, which is a command that is simply remapped to cmd-d, and see how that works for you?

**Comment by dsifford** [comment]
@johnfn Sure

```
$ code --version
1.8.1
```

![image](https://cloud.githubusercontent.com/assets/5240018/22216223/370e6628-e16c-11e6-9324-74929e1584f5.png)

Below is the `gc` command. Appears to just highlight the single instance of the word. Not sure how to extend that to repeat instances of the word.

![2017-01-23_13-03-23](https://cloud.githubusercontent.com/assets/5240018/22216284/76b71464-e16c-11e6-9ca6-37e4332ff47c.gif)

Can't really demo `cmd-d` because it literally doesn't do anything.

Hope that helps

**Comment by dsifford** [comment]
Update: If I `gc` and then `cmd+d` it works. If I double-click a variable in insert mode to highlight it and then `cmd+d`, it does not.

**Comment by johnfn** [comment]
I don't see any other instances of the words you're trying to gc in that gif. 

Could you send your settings.json? Also, you're up to date on vscodevim right (v0.5.1)?

**Comment by dsifford** [comment]
@johnfn Whoops, sorry. Thought I sent back a second update on this, but apparently I did not.

The issue on linux turned out to be the vim control key overrides still being enabled. Give me like 5 minutes to fire up my macbook and I'll see if that had something to do with my issue there as well.

**Comment by johnfn** [comment]
Makes sense. But `gc` should always work, even if `cmd-d` has been overridden.

**Comment by dsifford** [comment]
@johnfn Ah, ok sorry about that. The `gc` issue was a fundamental user error on my part. Didn't realize that I had to do `gc`, `gc`, `gc`, `gc`, etc each time. I thought there was a "repeat last command" operator built in for that (so `.`, or `n`, or something).... Anyway, mark that as 👍 

The `cmd-d` issue is persisting.

> Could you send your settings.json?

```json
// Place your settings in this file to overwrite the default settings
{
    "editor.fontFamily": "Monaco, 'Courier New', monospace",
    "editor.fontSize": 16,
    "rust.cargoHomePath": "/Users/dsifford/.cargo/bin/cargo",
    "editor.cursorBlinking": "blink",
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": [
                ":"
            ],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.showCommands",
                    "args": []
                }
            ]
        }
    ]
,
"typescript.check.tscVersion": false,
"vim.useSystemClipboard": true,
"vim.useCtrlKeys": false,
"files.associations": {
    ".stylintrc": "json5",
    ".babelrc": "json5"
}
}
```

> Also, you're up to date on vscodevim right (v0.5.1)?

Yep! Just updated this morning I think.

PS: Thanks so much for the help! I'm a newly converted atom-user still kicking the tires of VSCode, so there's a large probability that this is my fault. I appreciate your hospitality 😄

**Comment by johnfn** [comment]
Ah, I see. The problem is you have `"vim.useCtrlKeys": false,` when it should be `true` to capture our overwritten `cmd-d`.

> PS: Thanks so much for the help! I'm a newly converted atom-user still kicking the tires of VSCode, so there's a large probability that this is my fault. I appreciate your hospitality 😄

No worries! Always a pleasure to convert more people over to the dark side! Er, I mean the dark themed side. 😄

**Comment by johnfn** [comment]
Huh, I'm stumped! When I copy your configuration into mine, I can still do cmd-d.

What happens if you disable your other extensions and restart? Does it work then?

> PS: Thanks so much for the help! I'm a newly converted atom-user still kicking the tires of VSCode, so there's a large probability that this is my fault. I appreciate your hospitality 😄

No worries! Always a pleasure to convert more people to the dark side! Er, the dark themed side.

**Comment by dsifford** [comment]
@johnfn Disabled everything except VSCodeVim and still nada ☹️ 

Is there the a VS code equivalent of Atom's keybinding resolver to see what's happening when I actually hit those keys?

**Comment by karlhorky** [comment]
Should this be reopened? This appears to happen still now:

*vim extension enabled*

![1](https://user-images.githubusercontent.com/1935696/31501966-fc79795c-af6b-11e7-95e4-7a4955f3fa5b.gif)

*vim extension disabled*

![2](https://user-images.githubusercontent.com/1935696/31501950-f56d9cec-af6b-11e7-8256-dee58cee1919.gif)

**Comment by Chillee** [comment]
@karlhorky We don't currently have any way of providing support for "selections" in insert mode. Thus, when you do the drag, it stays in insert mode. If you want it to automatically go into visual mode, you can set `  "vim.mouseSelectionGoesIntoVisualMode": true`

**Comment by karlhorky** [comment]
@Chillee This is already set to true in my config (looks like this is the default).
