### ISSUE TITLE
Pressing <tab> still inserts the string "<tab>" sometimes

### ISSUE THREAD

**Issue by haf** [VSCodeVim/Vim#1195]
<img width="176" alt="screen shot 2016-12-25 at 22 24 58" src="https://cloud.githubusercontent.com/assets/193115/21472945/13c15dd8-caf1-11e6-8fe6-efd4187f8866.png">

**Comment by Zyst** [comment]
Yep, have the same issue.

Happens a handful of times a day to me, it's not a dealbreaker but it is annoying as hell.

**Comment by Zyst** [comment]
I dunno what triggers it, but it's becoming worse. 

Now it inserts the "<tab>" character until I restart VS Code. I think you never realize how much you use "tab" until something like this happens.

**Comment by johnfn** [comment]
This is unfortunately due to an unavoidable race condition due to a lack of information sent back from VSCode. I wrote a little explanation here: https://github.com/VSCodeVim/Vim/issues/875#issuecomment-252826237

**Comment by johnfn** [comment]
It's weird that this issue is gaining more thumbs up, because after I made a fix a few weeks back, I practically never encounter it (less than once every other week of all day coding, I'd say). 

If anyone thumbsing-up this issue could either provide

* Reproduction steps
* Or failing that, your settings.json file

it would be greatly appreciated!

**Comment by Zyst** [comment]
I'll share reproduction steps if I run into something that is reliably reproduce-able. 

Most of the time it seems random, but the occurrence has definitely lowered.

**Comment by likyng** [comment]
I can't really reproduce it reliably, but it happens extremely often for me. When I have been typing for 2/3mins without mode change it will definitly happen (on Arch Linux and Windows, latest everything).

Furthermore, when in the <tab> insert mode, the END, POS1 and DELETE keys won't work anymore until I have pressed escape, and then go back into insert mode, which is extremely annoying.

I think I'll switch back to the VScode version from mid december which did not have that problem..

**Comment by johnfn** [comment]
@likyng are you saying that you stay in insert mode for a long time, and then you begin to see the tab character more?

**Comment by pitkane** [comment]
Same here, happens often when insert mode is "left on" in certain file, and  after surfing through other files and coming back to that origin file <tab> thing happens. Very hard to reproduce reliably, sorry :( MacOS 10.12.2, Code 1.8.1, Vim 0.4.10 (latest)

**Comment by matwood** [comment]
I used the split editor, followed the steps listed by @pitkane and also was able to reliably reproduce the issue.

1. Open a split editor.
2. Make sure both editors are in normal mode and looking at 2 different files (Untitled-1 and Untitled-2).
3. Turn on insert mode for one split editor (Untitled-2).
4. Go to the other split (Untitled-1) and turn on insert mode and turn it back off.
5. Go back to the original split (Untitled-2) and hit tab.

**Comment by okoriko** [comment]
@johnfn similarly to what @matwood described  (step 1-3 are the same), I can reliably reproduce it with:
1. Open a split editor.
2. Make sure both editors are in normal mode and looking at 2 different files (Untitled-1 and Untitled-2).
3. Turn on insert mode for one split editor (Untitled-2).
4. Click to set the caret position elsewhere on the same document (Untitled-2).
5. Hit tab and the characters `<tab>` will be written.

**Comment by johnfn** [comment]
Wow, thank you both for the phenomenal reproduce steps! I see the problem is that there were actually two different ways that `<tab>` could be inserted, but I had only fixed one of them. This will make things much easier. Thank you!

**Comment by johnfn** [comment]
Fixed and because I realize this was driving a lot of you nuts I immediately pushed out 0.4.11 with this fix.

Thanks again!

**Comment by okoriko** [comment]
@johnfn thank you!

**Comment by godbout** [comment]
Still having the issue here, happening very, very often. Usually after I run some tests in the integrated terminal, or when I format the current document. Any way to help point out where might be the issue?

**Comment by jpoon** [comment]
Fixed https://github.com/VSCodeVim/Vim/pull/2320. At an airport right now, will push a release when I get better wifi.

**Comment by godbout** [comment]
Airports. The best place to be creative 😍️😂️

Thank you!

**Comment by jpoon** [comment]
@Chillee Moving your discussion comment from https://github.com/VSCodeVim/Vim/issues/831#issuecomment-362878696 here as we closed that issue as a dupe.

Do we care about `<tab>` in a widget? https://github.com/VSCodeVim/Vim/blob/master/package.json#L126? Should it be `editorTextFocus`?

**Comment by Chillee** [comment]
@jpoon whups. We don't, and I don't think the issue of whether we capture tabs or not in tabs is really related.

I'm pretty sure the issue is that we're setting the context `vim.mode` at multiple different places, and it's possible for the `<tab>` to be captured because `vim.mode` is in normal mode, when we're really in insert mode.

**Comment by Chillee** [comment]
@jpoon Huh. Removing the await here: https://github.com/VSCodeVim/Vim/blob/68e793fb25254e14bbb4823ccc28dd500af8feb0/src/mode/modeHandler.ts#L1350

not only seems to solve the `<tab>` case for the repro I posted above, it also seems to provide performance improvements as well.

**Comment by jpoon** [comment]
Funny, I was thinking of doing that exact same change and reviewing our overall usage of `await`. Great to hear that it's better. But I wonder if that'll expose timing issues.
