### ISSUE TITLE
Ctrl-D and Ctrl-U do not update cursor correctly

### ISSUE THREAD

**Issue by tiehuis** [VSCodeVim/Vim#1348]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Use Ctrl-D and Ctrl-U as movement keys. Also affects Ctrl-f and Ctrl-b.

### What did you expect to happen?

The cursor should retain its relative position on the screen (disregard the edge of file case) during Ctrl-D and Ctrl-U movement.

### What happened instead?

The cursor position is not updated within the file and drops off the visible portion of the screen. On the next successive movement there appears to be some check for an out of bounds cursor which places it to the bottom of the screen regardless of its initial position.

This makes movement with these keys unusable.

### Technical details:

Pretty certain this a regression since VSCode 1.9 which did not have this problem. Doesn't appear to be any recent issues on VSCode itself relating to movement right now so not sure who the cause of this is.

* VSCode Version: 1.10
* VsCodeVim Version: 0.5.3
* OS: Arch Linux + Windows 10

**Comment by johnfn** [comment]
Interesting - are you saying that this begun happening after the latest vscode release? 

Until we solve this correctly, you can use the workaround found here https://github.com/VSCodeVim/Vim/issues/907#issuecomment-264738452 to redefine c-u and c-d. A lot of people rely on these motions, so we'll try to get there quickly!

**Comment by JessThrysoee** [comment]
Upgrading to Visual Studio Code Version 1.10.1 did not fix this for me.

**Comment by gwojan** [comment]
@johnfn "Interesting - are you saying that this begun happening after the latest vscode release?"

Yes, this behavior just started with 1.10.1. I was using the Insiders release and noticed something funky but it didn't really hit me until I updated to 1.10.1 non-Insiders earlier today.

**Comment by rhys-vdw** [comment]
FWIW I have this problem on `1.10.0`. I haven't yet restarted to update.

**Comment by gwojan** [comment]
I guess I should've mentioned I did not see the problem on 1.9.1. 😉

**Comment by johnfn** [comment]
It sounds a lot like this is a regression in VSCode itself. We've got our best men (aka @rebornix) on it. :)

**Comment by mrtoniliu** [comment]
It seems this problem is resolved in VSCode 1.10.2.

**Comment by gwojan** [comment]
@johnfn I'm still not sure scrolling is working correctly. ```Ctrl-d```, ```Ctrl-u```, ```Ctrl-f```, ```Ctrl-b``` do not scroll down like gvim.

With the cursor at the start of the document pressing ```Ctrl-f``` locates the cursor at the bottom of the screen. Pressing ```Ctrl-f``` a second time moves the current line to the top of the visual window.

```Ctrl-f``` in gvim scrolls by one screen-height of text with each press. I'm currently using Windows 7 and haven't checked Windows 10 yet.

**Comment by rebornix** [comment]
The fun part is setting below keybindings 

```
    {
        "key": "ctrl+f",
        "command": "editorScroll",
        "when": "editorTextFocus",
        "args": {
            "to": "down",
            "value": 1,
            "by": "page",
            "revealCursor": true
        }
    }
```

is perfect. However in Vim, we just call this command but the behavior is different. I'll take a look.

**Comment by johnfn** [comment]
If you think `ctrl-d` and `ctrl-u` have gotten WORSE as compared to before this specific bug was introduced, *please thumbs this specific comment up.*

We know they're still not really optimal. That is unfortunately a limit of vscode right now.

**Comment by snewell92** [comment]
Can confirm on VSCode 1.11.2 with vscodevim 0.6.20; <C d> <C u> will move the cursor half a page down, which only moves the page down every other time I press it. 😢This seems to be the same behavior @gwojan observed with <C f>.

**Comment by Chillee** [comment]
@snewell92 Is the `<C-e>` and `<C-y>` resolved for you now? It was reported somewhere else, and they reported that the most recent vscode release fixed that issue.

**Comment by snewell92** [comment]
Yep! Can confirm resolution. Tyvm <3<3

**Comment by Chillee** [comment]
I don't really get what the bug is here. I can't really replicate the exact bugs that most people are talking about with `<c-d>`.

I do have the issue where `<c-d>` moves the cursor to the top of the screen, but that seems like more this issue: https://github.com/VSCodeVim/Vim/issues/1348

**Comment by snewell92** [comment]
@Chillee did you mean to reference another issue, you linked to this issue.

Originally @tiehuis said

>The cursor should retain its relative position on the screen [when using <c-d> <c-u>

I was trying to generalize the problem to see if there was an underlying problem with how navigation movements worked, but that doesn't appear to be the case.

It seems to me that the this issue is now focused on the cursor position in `<c-d>` and `<c-u>`.

**Comment by Chillee** [comment]
Oh I meant to comment on a different issue.

**Comment by boydy12** [comment]
Stopped working with 1.15 but updated to 1.15.1 its working again.

**Comment by boydy12** [comment]
This needs reopening.

I am finding this issue occur on certain files but not others. One html file that I have the behaviour described at the top of this post occurs, but on another html file works perfectly.

Intermittent issue but it is consistent with the file. Tried opening and closing VS Code closing the file and reopening. 

Nothing really special about the file in question, just a html file with angularjs.

VS Code version: 1.15.1

**Comment by Chillee** [comment]
@boydy12 This issue doesn't seem to be closed to me?

I think it's a vscode limitation; hold off on that while I check though.

**Comment by rpeshkov** [comment]
As a workaround you can define those bindings:

    {
        "before": ["<C-d>"],
        "after": ["j","j","j","j","j","j","j","j"]
    },
    {
        "before": ["<C-u>"],
        "after": ["k","k","k","k","k","k","k","k"]
    }

Looks weird, but works :)

**Comment by iwaffles** [comment]
I've noticed this happening when the file is taller than the window height and your cursor is near the bottom of the view. For me, it won't move the cursor up as it does in vim, atom (with vim keybindings), etc.

**Comment by HACK21** [comment]
@rpeshkov  #907 provide a simple way

```
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["<C-u>"],
            "after": ["2", "0", "k"]
        },
        {
            "before": ["<C-d>"],
            "after": ["2", "0", "j"]
        }
    ]
```

**Comment by KarboniteKream** [comment]
I have a problem with visual line selection and <C-u>.

If I select a line and then move a few pages up with <C-u>, the selection does not start with the line I initially selected, but it starts from the bottom of the screen. <C-d> seems to be working fine. 

Is this related to this issue?

**Comment by c10b10** [comment]
What is the status of this issue?

**Comment by c10b10** [comment]
I hacked a fix to issue (that works in Visual mode as well), using the macros plugin, and defining the following two macros in settings:

```json
"macros": {
        "vimCtrlU": [
            {
                "command": "type",
                "args": {
                    "text": "2"
                }
            },
            {
                "command": "type",
                "args": {
                    "text": "1"
                }
            },
            {
                "command": "type",
                "args": {
                    "text": "k"
                }
            },
            {
                "command": "type",
                "args": {
                    "text": "z"
                }
            },
            {
                "command": "type",
                "args": {
                    "text": "z"
                }
            }
        ],
        "vimCtrlD": [
            {
                "command": "type",
                "args": {
                    "text": "2"
                }
            },
            {
                "command": "type",
                "args": {
                    "text": "1"
                }
            },
            {
                "command": "type",
                "args": {
                    "text": "j"
                }
            },
            {
                "command": "type",
                "args": {
                    "text": "z"
                }
            },
            {
                "command": "type",
                "args": {
                    "text": "z"
                }
            }
        ]
}
```

and then defining the following keybindings:

```
[
    {
        "key": "ctrl+d",
        "command": "macros.vimCtrlD",
        "when": "editorTextFocus && !inDebugRepl && vim.active && vim.mode != 'Insert'"
    },
    {
        "key": "ctrl+u",
        "command": "macros.vimCtrlU",
        "when": "editorTextFocus && !inDebugRepl && vim.active && vim.mode != 'Insert'"
    },
    {
        "key": "ctrl+d",
        "command": "-extension.vim_ctrl+d",
        "when": "editorTextFocus && vim.active && !inDebugRepl"
    },
    {
        "key": "ctrl+u",
        "command": "-extension.vim_ctrl+u",
        "when": "editorTextFocus && vim.active && vim.use<C-u> && !inDebugRepl"
    }
]
```

**Comment by jpoon** [comment]
I didn't see the upstream issue on VSCode so I filed one. Please put a thumbs-up or something on https://github.com/Microsoft/vscode/issues/50264 if you want to see this get fixed.

**Comment by joeynguyen** [comment]
@c10b10 thanks for that "hack"! it works for me how I expect the VSVim plugin should work

**Comment by Vandell63** [comment]
Same Issue for me but fixed with disabling the smooth scrolling !! 
`"editor.smoothScrolling": true"`

**Comment by robertdavid010** [comment]
@Vandell63 solved exactly issue for myself also. Would be nice if they worked together. I may try the hack above to see if that is the best workaround.

**Comment by heepster** [comment]
Smooth scrolling didn't fix it for me.  @HACK21's suggestion use to work for me, but has stopped with VSCode version `1.25`.  

I adapted @HACK21's keybinding, which works for me now: 

```
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["<C-u>"],
            "after": ["2", "0", "k"]
        },
        {
            "before": ["<C-d>"],
            "after": ["2", "0", "j"]
        }
    ],
```

**Comment by pycckuu** [comment]
I've tried all of the above but could not solve the issue. The cursor is jumping making use of the extension impossible for me. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1489583/49879053-69fb6f00-fe29-11e8-8642-a2228b4a0d05.gif)

**Comment by chriys** [comment]
Hi all,
I any of you is still experiencing this. What fixed mine was to have VScode let the vim extension to handle the `ctrl+u` and `ctrl+d` keys by setting.
```
"vim.handleKeys": {
    "<C-d>": true,
    "<C-u>": true,
},
```

**Comment by ericlarosa** [comment]
Still doesn't work after trying @chriys s fix

**Comment by golergka** [comment]
> 
> 
> Smooth scrolling didn't fix it for me. @HACK21's suggestion use to work for me, but has stopped with VSCode version `1.25`.
> 
> I adapted @HACK21's keybinding, which works for me now:
> 
> ```
>     "vim.normalModeKeyBindingsNonRecursive": [
>         {
>             "before": ["<C-u>"],
>             "after": ["2", "0", "k"]
>         },
>         {
>             "before": ["<C-d>"],
>             "after": ["2", "0", "j"]
>         }
>     ],
> ```

This fix worked for me, but I'm still upset that this issue stil exists with plugin's default settings and the issue on github is closed.

@jpoon I realize that you're all awesome people who don't owe us users anything and provide this plugin for free, so I don't feel I have the right to demand anything here. But I think it is reasonable to kindly suggest a humble opinion not to close issues that are still not, in fact, solved.

**Comment by J-Fields** [comment]
@golergka About 6 months ago I re-wrote this feature essentially from scratch, and it should work without issue now. If you're still having problems with the default setting, please file a new issue describing the behavior you're seeing.

**Comment by pycckuu** [comment]
I still have the same issues with the jumping screen as in the video I showed here.

**Comment by J-Fields** [comment]
@pycckuu Can you post your settings please?

**Comment by pranavprabhakar** [comment]
I'm on Mac 10.15.2, VSCode 1.45.1 and vscodevim 1.14.4.
Ctrl+D works as expected for me, that is cursor moves half page down. But Cmd+D (Select next occurrence) even though selects the next match, the cursor shows behaviour similar to the above video.

**Comment by J-Fields** [comment]
Ohhhhhh, @pycckuu @pranavprabhakar yes, Cmd+D (select next occurrence) does have this issue, but it's fixed in master. Ctrl+D (move down half-page) should work fine - if anyone is still having issues with it (@golergka?), let me know.

**Comment by pycckuu** [comment]
@J-Fields Thank you for your reply. When it is expected to be updated in the MarketPlace then?

**Comment by J-Fields** [comment]
There will probably be a patch release later this week.

**Comment by pycckuu** [comment]
Unfortunately, I am still having issues even with an update.

**Comment by J-Fields** [comment]
@pycckuu Is the behavior unchanged?

**Comment by pycckuu** [comment]
Yes, it is the same as in the video, unfortunately.
