### ISSUE TITLE
ZZ example on the main page does not save in 1.10.2

### ISSUE THREAD

**Issue by eddy-geek** [VSCodeVim/Vim#1397]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Copy this to settings.json then press Shift+Z twice.
```
"vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["Z", "Z"],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.files.save",
                    "args": []
                },
                {
                    "command": "workbench.action.closeActiveEditor",
                    "args": []
                }
            ]
        },
```

### What did you expect to happen?
Saves and closes file.

### What happened instead?

The standard vscode "Save? Yes/No/Cancel" dialog is shown. As if the first command didn't run (or maybe didn't finish?)

Note that unlike #1222, the hotkey half-works (if I then press enter, the file is saved)

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.5 latest
* OS: Linux (Fedora latest)

**Comment by xconverge** [comment]
Interesting, thanks for the report!

**Comment by johnfn** [comment]
Fixed.

**Comment by luangong** [comment]
@eddy-geek Can you please re-open this issue? It seems that the `ZZ` keybinding still executes the two commands asynchronously. But the `ZZ` keybinding works as expected if I run the latest (96534ba4659cc0fcbde877ee012452c6d8cac23d) extension in debug mode.

### Technical details:

- VSCode Version: 1.15.1
- VSCodeVim Version: 0.10.0
- OS: macOS Sierra 10.12.6

**Comment by eddy-geek** [comment]
I don't see any re-open button, I guess @johnfn would have to do that.

Otherwise I just tested and I can confirm the issue persists, I still see the Save dialog.

Technical details:
* VSCode Version: 1.15.1
* VSCodeVim Version: 0.10.0
* OS: Linux Fedora 26

**Comment by sjackman** [comment]
Since `ZZ` is a standard vim command, why isn't it enabled by default in VSCodeVim?

**Comment by MikeyBeez** [comment]
It's my question too.  I'm afraid to map this, since you haven't done it yourselves.  Is there a reason not to map ZZ to save quit or, even better, just save?

**Comment by MikeyBeez** [comment]
This works:  "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["Z", "Z"],
            "commands": [
                ":wq"
            ]
        }
    ]

**Comment by MikeyBeez** [comment]
I found it here:  https://github.com/VSCodeVim/Vim/#key-remapping

**Comment by y0n3t4n1** [comment]
I use `ZZ` instead of `:wq` most of the time when I'm working on vi/vim because 1) it's easier to type, and 2) it only writes to the file when there's unsaved modifications.  I doubt the latter can be achieved simply by adding a key binding.

**Comment by J-Fields** [comment]
> I use `ZZ` instead of `:wq` most of the time when I'm working on vi/vim because 1) it's easier to type, and 2) it only writes to the file when there's unsaved modifications. I doubt the latter can be achieved simply by adding a key binding.

In fact, VSCodeVim can't save a file that doesn't have modifications (#1282)

**Comment by J-Fields** [comment]
I'm closing this as a duplicate of #5998 - users shouldn't have to worry about this, it should just work out of the box.

**Comment by MikeyBeez** [comment]
I just reinstalled VSCode, and ZZ works out of the box.  This IDE just gets better and better.
