### ISSUE TITLE
Add next occurence in insert and normal mode is limited to a maximum of 2 cursors

### ISSUE THREAD

**Issue by RodrigoRoaRodriguez** [VSCodeVim/Vim#1467]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
Go to ~either normal or~ insert mode and press _Add next occurence_ more than two times. 
For instance press it four times for the following text (the pipe `|` represents a cursor)
```
cursors|[1] = 1
cursors[2] = 2
cursors[3] = 3
cursors[4] = 4
```

### What did you expect to happen?
I expected a new cursor to be added for every press.
```
cursors|[1] = 1
cursors|[2] = 2
cursors|[3] = 3
cursors|[4] = 4
```
### What happened instead?
Only one new cursor is created, and after that _Add next occurrence_ no longer adds cursors or seems to do anything.
```
cursors|[1] = 1
cursors|[2] = 2
cursors[3] = 3
cursors[4] = 4
```
### Technical details:
* VSCode Version: 1.10
* VsCodeVim Version: 0.6.13
* OS: OSX 10.11 (El Capitan)

### Additional notes
Strangely enough it works on visual mode. Curiously, more than two cursors can be added through other commands such as _Select all occurrences_ or `alt-click`

The `Cmd-d` shortcut seems to be disabled by default while in insert mode, however it seems that can be restored by adding `"vim.handleKeys": { "<D-d>":false}` to your configuration (This however breaks normal mode by limiting it to two cursors).

**Comment by johnfn** [comment]
This DOES work without making that change to your settings, right?

**Comment by RodrigoRoaRodriguez** [comment]
@johnfn the change to the configuration is only necessary to trigger _Add next occurrence through the default shortcut (however without it it could still be activated through other means such as the menu item). I will edit the issue to be clearer in this regard so that no further misunderstandings occurs .

**Comment by johnfn** [comment]
cmd-d works perfectly for me on OSX, no configuration changes required! Do you not experience the same?

**Comment by xconverge** [comment]
Yea I would not recommend that configuration change since I think we are handling it better for our usage, I was just saying it could be tried

**Comment by RodrigoRoaRodriguez** [comment]
@johnfn and @xconverge `cmd-d` does not work for me while I am in insert mode without that configuration change. I tried it in two different computers.

**Comment by xconverge** [comment]
Yea that should be a separate bug report, should be pretty straightforward!

**Comment by RodrigoRoaRodriguez** [comment]
On February 18, I created such an issue(#1311) for the `cmd-d` shortcut not working in a previous version of VSCodeVIM.

**Comment by RodrigoRoaRodriguez** [comment]
* VSCode Version: 1.10
* VsCodeVim Version: 0.6.13
Although undocumented, this seems to have been fixed for normal mode. However, if  `"vim.handleKeys": { "<D-d>":false}` is added to the configuration as a workaround for #1311 it breaks in the same manner as before.

**Comment by jsonMartin** [comment]
Saw this issue was closed out but was it fixed? 

I still can't use "Add next occurrence" in insert mode, same issue with only selecting two matches in insert mode. It only works in normal/visual mode for me.

**Comment by Chillee** [comment]
@jsonMartin How are you adding next occurrence?

**Comment by jsonMartin** [comment]
Hey @Chillee, thanks for the quick response!

Yeah, I'm running on version 0.7.1. I'm attaching a copy of the text I posted over in the "multi cursor feedback" thread, but long story short I have tried doing it with my mouse at the menu bar on top of the screen, and with multiple different keyboard shortcuts mapped to "Add Next Occurrence". Also fiddled with the settings, nothing really helped.

Multiple cursors and "Select All Occurrences" work fine in insert mode. 

Here's what it looks like when I try it:
![giphy](https://cloud.githubusercontent.com/assets/4033621/26433005/a6cc4c94-40b4-11e7-8e97-d42e2db3b050.gif)

**Comment by Chillee** [comment]
@jsonMartin Can you try `<D-d>`?

**Comment by Chillee** [comment]
Actually, sorry, I am able to reproduce this. However, I am a little bit about your gif. Are you using a method of adding next occurence that's different from the default keybinding?

The issue happens when the word that you're matching on is also a substring of another word. The thing that's messing it up in your gif is key and licenseKey.

If you have something like
```
key
key
key
licenseKey
key
```
it should add cursors up until you get to licenseKey

**Comment by jsonMartin** [comment]
Yeah, that's Command + D right? That's what I was actually doing in the demo above to try to select the next matching item.

I have another binding for Add Next Occurrence since Cmd+D was bound to "Duplicate line", but that wasn't working either. I rebound Cmd+D back to Add Next Occurrence to test this, and no change in behavior. Also played around with the **"extension.vim_cmd+d"** keybindings as well to no avail

**Comment by Chillee** [comment]
In your case, I think it's the dot right after key. Could you try it on a blank file with nothing after the words? 

And definitely open up an issue. This is a bug.

**Comment by jsonMartin** [comment]
OK, so just played around with this more, and learned some additional data points that might help:

- When adding next occurrence via the menu, it only adds two items max no matter what mode it is in (Insert/Normal/Visual). Have to use the keyboard shortcut for it to work properly in any mode. 
- Match case option has to be selected to not let the case difference mess up the next selection, otherwise it breaks at the first case difference match.
- If the "Match whole word" option is on, it completely breaks the Add Next Occurrence feature in Normal/Visual mode (makes the cursor go backwards).
- You're also right that the dot right after the key is causing the issue. All occurrences after the dot aren't found (this is something I need quite often as a lot of replacements I do are with the class dot syntax)

Recorded another example here:
![example2](https://cloud.githubusercontent.com/assets/4033621/26434164/e483b462-40bb-11e7-89b9-dfb5fe069e55.gif)

I can definitely open up an issue for this. Is there anything else that you can think of that I can do in the meantime, as this is a feature I use all the time? Thanks!

**Comment by Chillee** [comment]
@jsonMartin Unluckily, I don't think so. I'm not really sure how to fix the first one (and I'm not sure it's worth spending the time to do so, since I doubt people use it much).
I can't reproduce the second one. You're saying you have something like
```
foo
Foo
foo
```
and it doesn't work in normal or insert mode? Or do you mean something more like your original example, where you have
```
key
licenseKey
key
```
?

The third one is bizarre, I'll have to take a closer look at that one.

I know how to fix the 4th one. I should be able to fix them soon, and we're planning on pushing out a release in a couple days, so you shouldn't have to wait too long.

**Comment by Chillee** [comment]
Haha. While fixing these bugs, I actually found a bug in the default VSCode functionality.
```
foo|
foofoo
foo
```
If you press `ctrl-d` a couple times, VSCode won't match more than 2 cursors here.

**Comment by Chillee** [comment]
Alright I fixed the main issues over here: https://github.com/VSCodeVim/Vim/pull/1748

So when you have time to make an issue, I'll merge the PR.

**Comment by jsonMartin** [comment]
@Chillee Here's one more data point / issue I uncovered in addition to the dot breaking additional occurrences. 

When in Insert Mode and Match Case is OFF, no more occurrences can be added after the first case difference. When case is ON, it proceeds fine past the case difference. It works fine in Normal mode. 

Not sure if this particular issue was fixed by your PR, but this example might help illustrate what I'm talking about:
![vscodevim3](https://cloud.githubusercontent.com/assets/4033621/26466475/b6187922-4143-11e7-960f-b27e2be74c97.gif)

**Comment by Chillee** [comment]
I think the cause is that key is a substring, not that key is uppercase. 

For example, 
```
key
licensekey 
key
```
Doesn't work for me. And neither does
```
key
keylicense 
key
```

**Comment by jsonMartin** [comment]
Ah @Chillee  , you're right! It doesn't matter whether it is uppercase or not, it is based on substring. So if "Match Whole Word" option is on, it will correctly skip "licensekey" or "licenseKey" while in insert mode.

So the problem then is that when I switch back over to normal or visual mode, "match whole word" is causing the cursor to go backwards; this happens when using "gc" command or Add Next Occurrence keyboard shortcut. 

However, when I manually highlight the desired word (whether with a mouse, or keyboard) and then add next occurrence (rather than just pressing the shortcut in the middle of the word), it seems to find all the matches OK! The big caveat to this method I'm seeing is that after selecting the matching occurrences and trying to change or delete them, it is removing the character directly to the right (whether that's a space, or a period). To correctly select the whole word in visual/normal mode, the cursor has to be to the right of the word, which is why I believe when multiple cursors are added it's deleting the extra character — the only way I've found around this is that after selecting all occurrences in this mode, to hit the left arrow so it moves the cursor back before changing or deleting. If that doesn't make sense, please let me know and I can show an example.

I assume that the intended behavior is to be able to press the add next occurrence shortcut and cursors should be added in the same positions and edit the same spots not matter which mode the user is in.

**Comment by Chillee** [comment]
@jsonMartin Yep, you're right. I think I've fixed all the bugs on master except for the "whole word" one. I'll need to take another look at that one to figure out how to handle it.

**Comment by jsonMartin** [comment]
Awesome, thanks for all the hard work on this. Much appreciated, cheers!

**Comment by Chillee** [comment]
@jsonMartin We just pushed out a new release, so try that and see if that fixes your issues!

Note: We swapped around `gc` and `gb`, which matters in normal mode/visual mode.

**Comment by jsonMartin** [comment]
@Chillee Just checked out the new version, and looks like Insert mode multiple cursors is working perfectly for me now, fantastic! Thank you so much!

I'm still seeing that bug in normal/visual mode on the new version however (which is what I think you mentioned above in your comment about the "whole word" bug). Here's an example of what it looks like on my end just to be clear:
![vscodevim4](https://cloud.githubusercontent.com/assets/4033621/26471500/cbb41c56-4156-11e7-9b9f-bba49275e845.gif)
