### ISSUE TITLE
Formatting and undo (u) not behaving correctly

### ISSUE THREAD

**Issue by ksrb** [VSCodeVim/Vim#1737]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

**Environment**:

- **VSCode Version**: Version 1.12.2 (1.12.2)
- **VsCodeVim Version**: 0.7.1
- **OS**:  Mac OSX 10.11.6 (15G1421)

**What happened**:
1. `git clone -b gh-pages https://github.com/dhg/Skeleton`
2. Open index.html
3. <kbd>shift+alt+f</kbd>/`editor.action.formatDocument`
4. <kbd>u</kbd>

**Actual**: 
Nothing happens/code doesn't 'un-format'

**Expected**:
Code should 'un-format'/go back to original format

**Comment by ksrb** [comment]
Sorry didn't really follow the bug format as I'm unsure how to even word the bug.

Also you can open any sufficiently complicated html page and it should also have the same bug.

**Comment by Chillee** [comment]
What if you press `u` and then hold down `ctrl z` for a while?

**Comment by ksrb** [comment]
Nothing happens 😞.

**Comment by Chillee** [comment]
I'm fairly confident actually that if you hold down `ctrl-z` for long enough, it'll undo all the changes...

It's just that the our "undo" action doesn't undo everything, and it leads to a bunch more undo steps that `ctrl-z` is going through. At least on a smaller document (2000 lines or so, not very dense), holding down `ctrl-z` seems to do the trick...

A rewrite to our undo functionality is currently planned (whether it'll be by leveraging Neovim or Vscode's default undo, we're not sure): https://github.com/VSCodeVim/Vim/issues/1727

**Comment by ksrb** [comment]
Hmm I'm pretty sure holding ctrl-z doesn't work.

![may-22-2017 15-15-42](https://cloud.githubusercontent.com/assets/3750409/26330602/95b261a0-3f01-11e7-814e-ff19ac929cba.gif)

Welp if you're sure this is going to fixed by https://github.com/VSCodeVim/Vim/issues/1727 then I guess I'll just wait :|.

**Comment by Chillee** [comment]
On the same file, it seems to work for me.
![tmp](https://cloud.githubusercontent.com/assets/6355099/26330839/f115b28a-3f1b-11e7-9606-ed034dba2bdc.gif)

After calling the command, I press `u` a couple of times, and then I start holding down `ctrl z`.

This issue (https://github.com/VSCodeVim/Vim/issues/1589) has the same root cause (I think), but it'll be solved due to neovim integration.

The issue you're talking about needs to be fixed by fixing up undo somehow.

**Comment by ksrb** [comment]
Oh okay thanks I wasn't holding down <kbd>cmd + z</kbd> long enough 😝. Well I guess since you guys are aware of this issue I'll close this?

**Comment by Chillee** [comment]
@ksrb Haha well it's definitely a bug and really bad on our part :P. I think we should keep it open for now, as there isn't another issue exactly tracking this. (The other one I linked is fixed by https://github.com/VSCodeVim/Vim/pull/1725)

**Comment by larslue** [comment]
Hi, this is still an issue for me. The Black formatter for Python does not support "Format selection", but only "Format document"
![image](https://github.com/VSCodeVim/Vim/assets/16062128/e9a8b154-1ce6-48eb-99c4-ff54b3a7f582)

So I resort to using "Format document", or Ctrl + Shift + I from the command panel. After formatting, I need to be aware to not press `u` by accident since the undo operation likely breaks the document.

I assume this bug is caused by the fact that `Ctrl + Shift + I` is not piped through the Vim plugin, so the plugin is not aware of the formatting action.

Would it be possible to add a keyboard shortcut to the Vim plugin to "Format document". e.g. `=ie` or similar? And document it extensively.

Would this fix the issue?
