### ISSUE TITLE
Using mouse in insert mode causes VIM to think it is in normal mode

### ISSUE THREAD

**Issue by kjgoodrick** [VSCodeVim/Vim#2410]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**: When in insert mode using the mouse to move the cursor causes the cursor to switch to block and the mode "changes" to normal; however, VIM is actually in insert and as soon as any letter is pressed the mode "switches" to insert and the character(s) are inserted. If the user settings file is open the cursor behaves as expected.

**What did you expect to happen**: Stay in insert mode, cursor remains a line and moves to clicked location. This happens if the user settings file is open.

**How to reproduce it (as minimally and precisely as possible)**: be in insert mode click anywhere else in the document.

This has also been reported by christiangenco [here](https://github.com/VSCodeVim/Vim/issues/1871#issuecomment-369363878) (Includes a video).

**Environment**:
- Extension Name: vim
- Extension Version: 0.11.0
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.20.1

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 283,
		"activateCallTime": 2,
		"activateResolvedTime": 19,
		"activationEvent": "*"
	}
}
```

**Comment by christiangenco** [comment]
I've been having the same bug and it's driving me absolutely crazy. Here's [a screen recording of it happening to me](https://www.youtube.com/watch?v=9JUkdspipQw&feature=youtu.be).

No joke I feel like I'm having a stroke every time it happens.

**Comment by Chillee** [comment]
I can't seem to reproduce this. Could you confirm that something we did in the last release didn't somehow fix it?

**Comment by jpoon** [comment]
Can't repro on my end with 0.11.1

**Comment by ivanvoznyakovsky** [comment]
this is fixed in last release of the extension but the fixe introduced another bug. now when you in insert mode and change cursor position by clicking status bar is blinking showing normal mode and that going back to insert mode.

**Comment by christiangenco** [comment]
@ivanvoznyakovsky's bug is happening to me too (and was happening before 0.11.2).

Here's [another video of it happening](https://youtu.be/BzAPnMtnOeY). Again, strangely, it's fixed if I open the settings window.

Here are the plugins and versions I have installed:

<img width="424" alt="screen shot 2018-03-10 at 5 30 19 pm" src="https://user-images.githubusercontent.com/179361/37247890-01f37d82-2489-11e8-9dd9-8d6972c134d9.png">

I've gone back to Atom because of this bug, but I'll hold out and switch back if it gets fixed :/

**Comment by kjgoodrick** [comment]
I am also no longer experiencing this bug. Thanks!

**Comment by ivanvoznyakovsky** [comment]
no idea why but have it all the time today. both blinking of status bar and block cursor in insert mode.

**Comment by christiangenco** [comment]
I've still got it, even after uninstalling all other plugins.

**Comment by dmolokanov** [comment]
Any updates on this issue yet? It's really annoying one when swap back and forth between vscode and neovim.
I have `vim.mouseSelectionGoesIntoVisualMode = true` in my settings
1. When I'm in `normal` mode and select a text with double click on word on select with mouse drag it puts editor in `visual` mode as expected.
2. When I'm in `insert` mode and do the same it still preserves `insert` mode

**Comment by berknam** [comment]
@dmolokanov What you are mentioning is a different issue #5716, it is better fixed with SelectMode that is not implemented yet but is being worked on.

As for the original problem of this issue, I can't reproduce it and I don't think it is a problem anymore. So I'm closing this one. But if anyone is still experiencing this issue feel free to comment and we will reopen if needed.

**Comment by fadedbee** [comment]
I'm also seeing this.  It only started this morning.

**Comment by fadedbee** [comment]
Sorry, I've uninstalled vscodevim, restarted vscode and I still get the same problem: the current word is dimly selected all over the file, but nothing else when I drag the mouse with the left-button held down.
