### ISSUE TITLE
Cursor move above or down with line indent

### ISSUE THREAD

**Issue by WangRongda** [VSCodeVim/Vim#2458]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG
**What happened**:
Note: The second line start with a indent.
Default(disabled vim plugin):
![foo](https://user-images.githubusercontent.com/22711444/37642736-44085b16-2c59-11e8-8063-54300dea1aa7.gif)
enable vim plugin:
![foo2](https://user-images.githubusercontent.com/22711444/37642760-570cbd42-2c59-11e8-96f2-16796d31a455.gif)
or Insert mode:
![foo3](https://user-images.githubusercontent.com/22711444/37642855-a421bbd2-2c59-11e8-8c47-a0652e6ccff2.gif)
Visual mode:
![bar2](https://user-images.githubusercontent.com/22711444/37642918-e279af48-2c59-11e8-81cf-7633883b06bb.gif)

**What did you expect to happen**:
Like vscode default show or native vim.
**How to reproduce it (as minimally and precisely as possible)**:
Use multi cursor instead of vim visual mode, but that has some problem too.

**Environment**:

- Extension (VsCodeVim) version:
- VSCode version:
- OS version:

**Comment by RYO0115** [comment]
I have the same issue with my vim plugin and it happens in any lines.

**Comment by gngshn** [comment]
I have the same issue, it sames because of vscode vim thinking tab width is 1.
if you set tabwidth=1 or replace tab to space. it will be OK!

**Comment by champignoom** [comment]
not sure if it's helpful but here's a similar yet solved issue of vscode-neovim: <https://github.com/asvetliakov/vscode-neovim/issues/275>

**Comment by falsandtru** [comment]
I confirmed https://github.com/asvetliakov/vscode-neovim works correctly. Can you adopt the same workaround?

**Comment by falsandtru** [comment]
Since Golang forces us to use tabs, using Golang is very painful because of this bug.

**Comment by xiany** [comment]
Dear. contributers

Hello. I'm not a typescript developer.
But, I think...

The getWord function should be modified in textEditor.ts

+ private static readonly tabRegExp = new RegExp('\\t');
+ let editorTabsize = editor.tabSize;

<before>
    while (this.whitespaceRegExp.test(line[firstNonBlank])) {
	  firstNonBlank++;
    ......


<after>
    while (this.whitespaceRegExp.test(line[firstNonBlank])) {
	  if (this.tabRegExp.test(line[firstNonBlank])){
		firstNonBlank += editorTabsize;
	  }else{
		firstNonBlank++;
	  }
    ......

**Comment by xiany** [comment]
In position.ts,
The value of 'character' is different from the 'Col' value on vscode status bar.
So the getLeft() function returns wrong horizontal position.

**Comment by ontanj** [comment]
this was fixed in #8756

**Comment by OiYouYeahYou** [comment]
@ontanj Are you sure that PR fixes the issue? I'm on `1.29` and cursor still does not stay in the column and assumes tabs are 1 width

**Comment by calbonaler** [comment]
This issue also occurs in `1.30.1`, not only for tabs but also for full-width East Asian characters such as Han and Kana.
