### ISSUE TITLE
snippets placeholder transform not working

### ISSUE THREAD

**Issue by unordered** [VSCodeVim/Vim#3176]
**Describe the bug**
snippets placeholder transform not working

**To Reproduce**
```
"HelloWorld": {
	"prefix": "test",
	"body": "${1} ${2} -> ${1/Hello/Hallo/} ${2/World/Welt/}"
}
```

**type**
Hello World -> Hello World

**Expected behavior**
Hello World -> Hallo Welt

it's work after disable vim plugin!

**Comment by idhamhafidz** [comment]
I have the same problem. After uninstall this extension, the snippets seems to be working again.
To reproduce, create multiple same variable in snippets like console.log(${variable1}, ${variable1}).
Whenever you want to enter something at the variable, it will fail.

**Comment by redforks** [comment]
Here too.

**Comment by trcolgrove** [comment]
Pleaser Help!

**Comment by zhuanhao-wu** [comment]
Same here!

**Comment by MrMarc** [comment]
man - I wish that I'd found that other people were having this same problem before I racked my brain trying to figure out what I was doing wrong.

i.e. me too

**Comment by 5argon** [comment]
Me too!

**Comment by prurph** [comment]
Also struggling with this. As a workaround you can use the left then right arrow keys to sync the cursors, then use backspace to delete the placeholder, then type your desired text.

**Comment by 5argon** [comment]
Hi, I am already using that workaround for cursor sync problem. This
problem however is placeholder **transform**. (the content change one last
time when you press enter)

 I have not found any workaround to make it work other than turning off vim
on using the snippet

2019年3月24日(日) 6:35 Prescott Murphy <notifications@github.com>:

**Comment by sloria** [comment]
This is quite an annoyance.

> I have not found any workaround to make it work other than turning off vim on using the snippet

@5argon  Is there a way to do this automatically? Or do you manually toggle off vim mode before entering every snippet?

**Comment by TW80000** [comment]
Can't speak to how features compare, but [this Vim plugin](https://marketplace.visualstudio.com/items?itemName=auiworks.amvim) is the second most installed Vim plugin for VS Code at the time of writing and it doesn't have this issue.

**Comment by kkirke** [comment]
I found a workaround that makes it much less annoying: In the keybindings for the command "extension.vim_backspace" add to the When clause "!editorHasSelection".

This allows you to press backspace and delete the things that are automatically highlighted during the snippet process.

The only downside is if you had anything hooked up to backspace in Visual Mode it will no longer work.

**Comment by taybin** [comment]
@lunawarrior This works, but I found that it enables deleting with the backspace when in Visual Mode, which feels weird.  I tried adding some more toggles to the When clause, but couldn't find a combination that would keep the previous behavior.

**Comment by gergelyth** [comment]
@J-Fields This appears to be fixed on the current master (at least the example in the first post is working for me).

**Comment by m4hi2** [comment]
@gergelyth I'm still facing this issue. I have just land on this thread while trying to figure out what is wrong.

**Comment by J-Fields** [comment]
Thanks @gergelyth, this is indeed fixed on master.

**Comment by gennaro-tedesco** [comment]
Has this been released in the plug-in? I am still seeing the same old behaviour (namely the snippets not working as described in all comments above).

**Comment by J-Fields** [comment]
@gennaro-tedesco Yes, this should be fixed in the released version. Please file a new issue with repro steps if you've still got a problem with snippets.

**Comment by OpoOpo** [comment]
@J-Fields I still see this behavior

**Comment by MaciekBaron** [comment]
Issue still seems to be happening, vim enters visual mode and you can't use the snippet properly

**Comment by geirmolnes** [comment]
> I found a workaround that makes it much less annoying: In the keybindings for the command "extension.vim_backspace" add to the When clause "!editorHasSelection".
> 
> This allows you to press backspace and delete the things that are automatically highlighted during the snippet process.
> 
> The only downside is if you had anything hooked up to backspace in Visual Mode it will no longer work.

How did you do that?

**Comment by J-Fields** [comment]
I'd suggest instead of messing around with the underlying keybinding, just add this to your vimrc:

`vnoremap <BS> c`

**Comment by superzilong** [comment]
@J-Fields 
I got the same issue too.
The first workaround I tried is to use the key "c" to delete the selected words in visual mode and changed to insert mode.
However, sometimes click "c" for one time can work. Sometimes, need to click two times. I don't understand this...
So I thought out another solution: define a shortcut for "esc", "c", "i", "w", this will change to normal mode then delete the placeholder and change to insert mode.
