### ISSUE TITLE
Error when remapping to commands with name starting with "extension."

### ISSUE THREAD

**Issue by hiaux0** [VSCodeVim/Vim#3307]
**Describe the bug**
- With the debug log level I get the following console error
```
[Extension Host] error: Remapper: normalModeKeyBindingsNonRecursive. 
Invalid configuration. 
Command does not exist. before= ,;. command=extension.insertSemicolon. args=undefined..

// Note that my <leader> is space
```

I just got this bug one or two weeks ago, as remapping to commands starting with `exentension.` was working fine.

The command in question can be found via the shortcut settings and works fine with `ctrl+,`
![image](https://user-images.githubusercontent.com/30693990/50548563-78ca8a00-0c4f-11e9-8bbd-144fe71de2cb.png)

- Other extensions work fine, eg.
```
[Extension Host] debug: Remapper: normalModeKeyBindingsNonRecursive. 
loaded: before= ,b,c. command=bookmarks.clear. args=undefined.
```

![image](https://user-images.githubusercontent.com/30693990/50548651-87657100-0c50-11e9-99f7-226676536f2a.png)

**To Reproduce**

0. Extension `chrisvltn.vs-code-semicolon-insertion`
1.  Remap in 	
```
"vim.normalModeKeyBindingsNonRecursive": [
  {
    "before": ["<leader>", ";"], 
    "commands": [ {"command": "extension.insertSemicolon"} ]
  },
]
```
2.  Attempt to execute remapped command
3.  Nothing happens

**Expected behavior**
In 3. from steps to repro, the command should execute

**Screenshots**
![image](https://user-images.githubusercontent.com/30693990/50548658-a237e580-0c50-11e9-86f3-6a245e7d5956.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.17.3
- VSCode version: Version 1.30.1
- OS: MacOS Sierra 10.13

**Additional context**
- Leader is space
- I tried with `normalModeKeyBindings` as well, still same error

**Comment by jpoon** [comment]
Interesting. Do you mind trying an experiment? Can you try explicitly activate the extension by calling the `extension.insertSemicolon` command through the command palette, does the keybinding work now?

**Comment by zikkurat** [comment]
Yes, I have the same problem.

**Comment by hiaux0** [comment]
> Interesting. Do you mind trying an experiment? Can you try explicitly activate the extension by calling the `extension.insertSemicolon` command through the command palette, does the keybinding work now?

You mean here?
![image](https://user-images.githubusercontent.com/30693990/50566244-b3a7ed00-0d37-11e9-99f7-364d749c3c02.png)

Works normal on command call via command palette

**Comment by jpoon** [comment]
With https://github.com/VSCodeVim/Vim/pull/3296, we added a check on remapped commands to ensure that they were 'valid' commands. We get a list of valid commands through VS Code's `getCommands()` API call so it's interesting that `extension.insertSemicolon` is not in that list.

**Comment by jpoon** [comment]
Ah, ok. My suspicion was true. We load the valid commands on startup here (https://github.com/VSCodeVim/Vim/blob/d1261f25fbaab4d5e6067d8dc761c270c8375e1d/extension.ts#L316). VS Code lazy loads extension and so at that point, the `insertSemicolon` is not a valid command. Once you explicitly activate that extension, it'll then be OK.

**Comment by zikkurat** [comment]
Nothing needed to be done. After vscode was updated to 1.30.2, the problem was fixed.

**Comment by dcecile** [comment]
:thinking: Upgrading from VS Code 1.30.1 to 1.30.2 didn't fix it for me:

```json
    {
      "before": ["<leader>", "i"],
      "commands": [
        "python.sortImports"
      ]
    }
```

> `[Extension Host] warn: Remapper: normalModeKeyBindingsNonRecursive. before= ,i. command=python.sortImports. args=. Command does not exist.`
