### ISSUE TITLE
Ctrl-d at end of file shows error

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#3358]
**Describe the bug**

Press down C-d at end of file.

Shows error:

ModeHandler: error handling key=<C-d>. err=Error: Illegal value for `line`.

![image](https://user-images.githubusercontent.com/4033249/51055376-945d5b00-1594-11e9-8764-f419a088ccd2.png)

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:287 [Extension Host] error: ModeHandler: error handling key=<C-d>. err=Error: Illegal value for `line`. (at ConsoleForElectron.log (/Users/pine/.vscode-insiders/extensions/vscodevim.vim-1.0.1/node_modules/winston-console-for-electron/dist/index.js:22:21))
t.log @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:287
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:287 [Extension Host] TaskQueue: error running task. err=Error: Illegal value for `line`. (at TaskQueue.<anonymous> (/Users/pine/.vscode-insiders/extensions/vscodevim.vim-1.0.1/out/src/taskQueue.js:36:29))
t.log @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:287
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2511 ModeHandler: error handling key=<C-d>. err=Error: Illegal value for `line`.
t.onDidNotificationChange @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2511
```

**To Reproduce**

Press down C-d at end of file.

**Expected behavior**

No errors.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.1
- VSCode version: 1.30
- OS: macOS 10.13

**Additional context**

**Comment by xconverge** [comment]
This was fixed on master in #3347

**Comment by igorilic** [comment]
It's still happening for me when I am trying to write something in quokka TS file.

![image](https://user-images.githubusercontent.com/14258072/52169623-11b36000-273c-11e9-893d-c58482d10c6c.png)

**Comment by jpoon** [comment]
should be handled with https://github.com/VSCodeVim/Vim/pull/3442

**Comment by igorilic** [comment]
Now it's failing when I press any key in insert mode :(

![image](https://user-images.githubusercontent.com/14258072/52175163-21649000-27a0-11e9-8d85-c3a5a7979d1d.png)
