### ISSUE TITLE
Go to Line Using [line]+gg Throws Exception

### ISSUE THREAD

**Issue by k4yt3x** [VSCodeVim/Vim#3845]
## Description

When going to a line that doesn't exist, using line 100 in a document 90 lines long for example, using `100 + G` goes to the last line, where `100 + gg` throws an error and does nothing.

## Reproduce

In any documents, go to a line that doesn't exist using `[line number] + gg`.

## Expected Behavior

When going to a line that's out of bound, go to the last line, just like how vim behaves.

## Screenshots

![image](https://user-images.githubusercontent.com/21986859/59862535-7cbfa500-9372-11e9-9495-e5bcf4429dfc.png)

## Environment

- Extension Name: `vim`
- Extension Version: `1.8.1`
- OS Version: `Linux x64 4.19.0-kali5-amd64`
- VSCode version: `1.35.1`

**Comment by zhuzisheng** [comment]
I can reproduce this error.
Will try to fix.

**Comment by Stamo-Gochev** [comment]
I am experiencing a similar problem - an error is not thrown, but the navigation still fails. I see that the PR has been merged into master, so I suppose the issue should be closed and the fix will be out with the next version?

**Comment by k4yt3x** [comment]
I believe this problem has been fixed in #3845.

**Comment by Stamo-Gochev** [comment]
@k4yt3x Is this part of [1.8.2](https://github.com/VSCodeVim/Vim/releases/tag/v1.8.2). I've just upgraded and I am still not able to jump to the line. Can someone else recheck that?
