### ISSUE TITLE
Latest update breaks Intellisense navigation

### ISSUE THREAD

**Issue by flagbug** [VSCodeVim/Vim#414]
### Issue Summary

Since version `Massive Marshmallow`, up and down navigation in the Intellisense popup with the arrow keys doesn't work anymore. Maybe because of https://github.com/VSCodeVim/Vim/pull/387?

### Steps to Reproduce

1. Start typing a class
2. Press `Ctrl + Space`
3. Try navigating down in the Intellisense popup
4. The popup is exited instead

* VSCode Version: 1.3.0
* OS: Win 10 x64

**Comment by rebornix** [comment]
Oh that's a terrible mistake. Personally I'm not relying on the intellisense popup so I didn't catch it.

I'm not sure whether we can detect that we are in the intellisense mode or not, so my quick turnaround for now is disabling these arrows features in Insert Mode then look into it further more.

**Comment by rebornix** [comment]
And thanks for reporting this issue @flagbug

**Comment by johnfn** [comment]
Thanks for reporting the issue, @flagbug! It's been fixed in v0.1.1, which I just pushed out.

**Comment by flagbug** [comment]
Wow, that was fast, thanks!

**Comment by tanordheim** [comment]
I still have this problem in VSCode 1.3.1 using version 0.1.2 of this extension. It works for intellisense (ctrl+space), but for code corrections (command+.) the arrow key causes the cursor to move instead of navigating the popup list.

**Comment by johnfn** [comment]
@tanordheim How can I trigger the code corrections menu? I'm unfamiliar with this feature. Pressing cmd+. doesn't do anything - presumably because I don't have any code that needs to be corrected.

**Comment by tanordheim** [comment]
If you create a new C# file with the C# extension installed, looking like this:

```csharp
public class Test
{
    public void TestMethod()
    {
        Console.WriteLine("Hello, World!");
    }
}
```

Then `Console` should show an error (presuming omnisharp is active on the project), putting the cursor on the word and hitting cmd+. opens up a correction menu like this:

<img width="492" alt="screenshot 2016-07-14 08 08 20" src="https://cloud.githubusercontent.com/assets/49933/16829684/49c49ff4-499a-11e6-8a43-7b3eece01571.png">

**Comment by tanordheim** [comment]
Hi @johnfn, any update on this? I'm happy to produce a pull request for you on this if you could nudge me a little in the right direction; I'm not at all familiar with VSCode extensions and aren't really sure where to begin digging in order to help fix this :)

**Comment by johnfn** [comment]
@tanordheim ah, I'm really sorry. I'm not really a huge fan of the Github notification system and a lot of notifications seem to fall through the cracks.

It looks to me like up/down work from within insert mode. Is that sufficient for you? 

Normal mode may unfortunately be impossible for now. The VSCode API does not allow us to actually know if we have that window open.

**Comment by tanordheim** [comment]
Agreed, it's way easy to miss stuff :)

Yeah, this works in insert mode actually, that'll be sufficient for now - thanks!
