### ISSUE TITLE
Jupyter notebook mode

### ISSUE THREAD

**Issue by TyberiusPrime** [VSCodeVim/Vim#4156]
**Describe the bug**
The october update of vscode brought
a nice feature where jupyter notebooks run directly inside vscode,
see https://code.visualstudio.com/docs/python/jupyter-support.

Unfortunatly, vim mode is completely off when opening a .ipynb file.

**To Reproduce**
1. command palette - "Python: Create Blank New Jupyter Notebook"
2. Press enter to enter the default empty cell.
3. Observe missing vim mode.

**Expected behavior**
I'd expect entering a cell to drop me into normal mode, 
and 'escape' in normal mode to leave the cell.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.11.0
- VSCode version: 1.39.0
- OS: Ubuntu bionic

**Comment by J-Fields** [comment]
As far as I know, we have no control over this. Please file an issue with the VSCode team.

**Comment by thoo** [comment]
According to VSCode team, we should request the issue here. [#81812](https://github.com/microsoft/vscode/issues/81812)

>I believe this is more of a consequence of how the extension built the feature, you should go through their repo first and maybe VS Code could provide APIs to help support this.

**Comment by J-Fields** [comment]
Thanks for pointing that out @thoo. I actually think "the extension" refers to the python extension which enables the fancy view of notebooks. My understanding is that they use a webview so extensions within the cells won't work (see [this comment](https://github.com/microsoft/vscode-python/issues/5959#issuecomment-519163663) and [this older issue I just recalled](https://github.com/VSCodeVim/Vim/issues/3973)).

**Comment by thoo** [comment]
Thanks for clarification. If anyone looking for this information, here is the [issue #7866](https://github.com/microsoft/vscode-python/issues/7866) from vscode python-extension. As of now, vim mode is not supported at jupyter notebook files.

>Sorry but this isn't supported at this time. VS code extensions don't load in the notebook editor.
>See this other bug:
>#7875

**Comment by ishipachev** [comment]
Hi!
I have a good news. With new API Juptyer Notebooks got a better support from VS Code.
I just tried do all by instruction here: 
https://towardsdatascience.com/vscode-jupyter-notebooks-are-getting-an-upgrade-cc9aaaefc744
In this short article also an instruction of how to open jupyter notebook through fancy new fully supported mode.

And vim mode worked for me! It's no longer an issue.

**Comment by raoulg** [comment]
> Hi!
> I have a good news. With new API Juptyer Notebooks got a better support from VS Code.
> I just tried do all by instruction here:
> https://towardsdatascience.com/vscode-jupyter-notebooks-are-getting-an-upgrade-cc9aaaefc744
> In this short article also an instruction of how to open jupyter notebook through fancy new fully supported mode.
> 
> And vim mode worked for me! It's no longer an issue.

Well, I use:
- Python (microsoft) 2020.8.109390
- Vim (vscodevim) 1.16.0
- VS Code Jupyter Notebook Previewer 1.2.2

Even after disabling and restarting the last plugin, I still have this behavior:

- while editing a cell, and pressing ESC, I stop editing the cell. 

So no normal mode for ipynb.... How did you get this to work, exactly?

**Comment by rickyelopez** [comment]
I'm in the same boat as @raoulg... New insiders version of Jupyter integration is very nice, but I can't exit normal mode

**Comment by mvolkmann** [comment]
@raoulg The instructions at https://towardsdatascience.com/vscode-jupyter-notebooks-are-getting-an-upgrade-cc9aaaefc744 can only be read by people that pay for access to Medium. Could you add the relevant parts in this issue so I can see the steps to get Vim to work in Jupyter cells?

**Comment by dang-qi** [comment]
> @raoulg The instructions at https://towardsdatascience.com/vscode-jupyter-notebooks-are-getting-an-upgrade-cc9aaaefc744 can only be read by people that pay for access to Medium. Could you add the relevant parts in this issue so I can see the steps to get Vim to work in Jupyter cells?

I could read it by just register an account without paying.

**Comment by mvolkmann** [comment]
@dang-qi I think that's because you haven't read many Medium articles yet. I have hit the free limit and now need to pay $5/month to read more.

**Comment by rickyelopez** [comment]
> Get a First Look at These New Features
> 
> These features are available at the Insiders version of both VSCode and the Python extension. Put simply, here are the steps to enable these experimental features:
> 
>     Download & Install Visual Studio Code Insiders here.
>     Install the Python extension on the Extension manager.
>     Enable the Insiders Daily channel for the Python extension.
> 
> Image for post
> Image for post
> 
> That’s it! It’ll start installing and let you know to reload your VSCode Insiders after completion. Now, whenever you wish to open an .ipynb file with the new Jupyter Notebook UI, open the context menu (right-click on the file) and select “Open in Preview Notebook Editor”.

Note that following these instructions did not enable VSCodeVim for me, not sure how it worked for somebody else.

**Comment by mvolkmann** [comment]
Thanks @rickyelopez! I used to use VS Code Insiders but decided I didn't need the risk of daily updates breaking things. I think I'll wait until this is available in a stable version. But I'm glad to hear Vim support in Jupyter Notebooks should be coming soon!

**Comment by rickyelopez** [comment]
> 
> 
> Thanks @rickyelopez! I used to use VS Code Insiders but decided I didn't need the risk of daily updates breaking things. I think I'll wait until this is available in a stable version. But I'm glad to hear Vim support in Jupyter Notebooks should be coming soon!

Following those instructions did **not** work for enabling Vim support for me. Did they work for you?

**Comment by mvolkmann** [comment]
@rickyelopez I didn't try it because I prefer not to use the Insiders version of VS Code.

**Comment by rickyelopez** [comment]
> 
> 
> @rickyelopez I didn't try it because I prefer not to use the Insiders version of VS Code.

Gotcha.

@ishipachev can you comment on whether you did anything special to get this working after following those instructions?

**Comment by pietrodelugas** [comment]
Hi 
for me it works in wsl2, Ubuntu 20.4. Usinig it directly in Ubuntu it doesn't work.

**Comment by JosXa** [comment]
> @dang-qi I think that's because you haven't read many Medium articles yet. I have hit the free limit and now need to pay $5/month to read more.

Psssssst 🤫, _try incognito mode and thank me later_

**Comment by miwojc** [comment]
i installed vscode insiders and vim extension (by vscodevim) and now i have vim keybindings in jupyter notebook. however how can i get a list of keybindings, for example how do i enter jupyer mode, i assume we have three modes: jupyter mode, vim command and insert mode? thanks!

**Comment by virtu** [comment]
Insiders works for me, too; however, Insiders comes with too many other problems. Are there any plans to back-port the vim capability to regular VS Code?

**Comment by NightMachinary** [comment]
Is it the expected behavior that pressing `ESC` exits the cell? This breaks my muscle memory very badly ... (`C-c` still works fine, but I'm not used to it, and it's two keys.).

**Comment by tautomer** [comment]
Redo and undo not working? `U` returns "already at oldest change" and `C-r` returns "already at newest change".
I had to exit the cell and use `C-z` and `C-y` to do it and then go back to the cell for editing.

I'm using VSCode 1.56.0-insider and Python extension v2021.5.734046506-dev.

**Comment by Moh-Snoussi** [comment]
Hi, I have a good news. I am not going to give you an external site with 8/9 pages to solve the problem **vim mode on Jupyter notebook**.
Vim mode seams to work on **VS code Insider.** 
download and install VS code Insider from https://code.visualstudio.com/insiders/

**Comment by jrs65** [comment]
In case anyone was wondering this now seems to work in the August release of the straight up VS Code (i.e not Insiders).

It seems great to me, although the differences between the keybindings there and the jupyterlab-vim bindings are confusing my brain!

**Comment by fingertap** [comment]
I find the vim-jupyter mode transition kind of troublesome in some cases. 

For example, when I try to delete a row by typing `d` and suddenly I decide not to do it, usually I can cancel this `d` by `Esc`. However, in a jupyter notebook file, pressing `Esc` after pressing `d` enters the jupyter mode. If I press `Enter` to edit that cell again, that line is still waiting for me pressing `d` to delete. In other words, I cannot cancel a `d` operation, unless I delete it and then press `u`.

<img width="309" alt="image" src="https://user-images.githubusercontent.com/7274689/190893814-b4fb3e54-5ca1-4f66-9e19-ac16af7d074b.png">

**How can I change the keybindings of jupyter notebook?**

Another thing that bothers me is that, when cell A is in vim-normal mode, and cell-B is in vim-insert mode, and my cursor is at the last line of cell A, if I press 'j' for multiple times to try to move down to the next lines, I got this:

<img width="326" alt="image" src="https://user-images.githubusercontent.com/7274689/190893856-90066b14-234c-45cd-a872-c9b2b44a590d.png">

**How can I forbid the cursor moving between cells?**

**Comment by fingertap** [comment]
To change between jupyter mode and vim's normal mode, you can change the default key bindings for entering jupyter mode.

However, I find another issue of Vim mode in jupyter notebook. I do not want the cursor to move between cells. However, even if I uncheck the option `Notebook › Navigation: Allow Navigate To Surrounding Cells`, I still can move the cursor around when I am in Vim's normal mode. I cannot move to other cells in the insert mode though. Any ideas how to fix this?

**Comment by maptv** [comment]
VSCodeVim is working for me locally in Jupyter notebooks but not in Jupyter notebooks in Codespaces. In contrast, VSCode Neovim works both locally and in Codespaces.
Also, I have the opposite issue as @fingertap: the `Notebook › Navigation: Allow Navigate To Surrounding Cells` is checked and I cannot navigate between cells even I though desperately want to...

**Comment by maptv** [comment]
I fixed the inability to navigate between cells with some keybindings:
```
  { "key": "j", "command": "notebook.focusNextEditor", "when": "config.notebook.navigation.allowNavigateToSurroundingCells && neovim.mode == 'normal' && editorTextFocus && inputFocus && notebookEditorFocused && !accessibilityModeEnabled && !isEmbeddedDiffEditor && notebookEditorCursorAtBoundary != 'none' && notebookEditorCursorAtBoundary != 'top'" },
  { "key": "k", "command": "notebook.focusPreviousEditor", "when": "config.notebook.navigation.allowNavigateToSurroundingCells && neovim.mode == 'normal' && editorTextFocus && inputFocus && notebookEditorFocused && !accessibilityModeEnabled && !isEmbeddedDiffEditor && notebookEditorCursorAtBoundary != 'bottom' && notebookEditorCursorAtBoundary != 'none'" }
```
@fingertap, if you look for similar keybindings and remove them, it should fix your issue.

**Comment by sarangak** [comment]
@fingertap @maptv Thank you!

I found that Notebook: Focus Next Cell Editor for `J` had a when condition of:
```
editorTextFocus && inputFocus && notebookEditorFocused && vim.mode == 'Normal' && notebookEditorCursorAtBoundary != 'none' && notebookEditorCursorAtBoundary != 'top'"
```

Adding:
```
config.notebook.navigation.allowNavigateToSurroundingCells && editorTextFocus && inputFocus && notebookEditorFocused && vim.mode == 'Normal' && notebookEditorCursorAtBoundary != 'none' && notebookEditorCursorAtBoundary != 'top'"
```

to the beginning of the condition fixes it.  Repeat for the `K` keybinding.

**Comment by fingertap** [comment]
The bug that vim mode can cross the cell border in jupyter notebook still exists. My walkaround is to use the nvim extension.
