### ISSUE TITLE
Multiple selections do not work as expected

### ISSUE THREAD

**Issue by mikeraimondi** [VSCodeVim/Vim#417]
### Issue Summary

Only the first selection is operated upon when there are multiple selections.

### Steps to Reproduce

1. Have [multiple cursors](https://code.visualstudio.com/docs/editor/editingevolved#_multiple-selections) active with multiple selections. (I used CMD-D)
2. Notice that the status bar indicates "visual mode". In visual mode, an operator command will act upon all highlighted(selected) characters.
3. Type an operator command like "c" or "d".
4. Notice that only the first selection is acted upon.

* VSCode Version: 1.3.0
* OS: OSX 10.11.5

**Comment by johnfn** [comment]
I generally use `.` to repeat a command in multiple places. I have been thinking about a separate Vim mode for multiple selections. It'd be a bit of work because it's essentially a new mode that doesn't exist in Vim.

**Comment by dahjelle** [comment]
For whatever it is worth, the Vim emulation in both Atom and in Sublime Text works as I'd expect in this case: all selections are acting upon identically.

**Comment by jpoon** [comment]
@dahjelle unfortunately, the APIs that these IDEs expose are vastly different from each other. as a result, all the vim emulators are different beasts (ie. no shared code).

**Comment by johnfn** [comment]
Wow, this is getting more interest than I had previously anticipated. Bumping the priority up.

**Comment by frederickfogerty** [comment]
Just my 2c: This is the only reason I used amVim over this extension - on that extension it allows multi cursors.

**Comment by johnfn** [comment]
Alright, that is a large amount of support. I will do this immediately after I finish Visual Block mode.

**THE PEOPLE HAVE SPOKEN.**

**Comment by johnfn** [comment]
Update: Just merged visual block mode into master, so I'll be working on this next. 

No promises, but with any luck it won't take more than a week to implement.

**Comment by johnfn** [comment]
Working on it over here: #587

**Comment by johnfn** [comment]
Done!! Took a little longer than my initial estimate, heh.

**Comment by frederickfogerty** [comment]
You're a legend @johnfn, thank you!

**Comment by johnfn** [comment]
@frederickfogerty, what are the normal ways that you would trigger multiple selections in visual studio code? One that I know of is cmd-d - what other ways do you use frequently?

**Comment by frederickfogerty** [comment]
@johnfn I just use Cmd-d. In vim I use C-n (https://github.com/terryma/vim-multiple-cursors), but for VSCode I've just used Cmd-d.

**Comment by johnfn** [comment]
Cool! Cmd-d is actually the only one I've implemented so far, but the infrastructure is there for any other multicursor actions that people want added. :)

**Comment by BrutalSimplicity** [comment]
I am not seeing where this current behavior is implemented. I have version 0.0.28 on the MAC. Is this not in the stable build yet?

**Comment by andradei** [comment]
I'm on 0.5.1 and still seeing issues with multi-cursors (cmd+d).

**Comment by chrisnicola** [comment]
So how does this work actually. I see that I can use `CTRL-V` but in Vim I would then typically type `i` or `c` to begin editing. That doesn't seem to work here.
