### ISSUE TITLE
On put register is overwritten by selected text if register contains lines

### ISSUE THREAD

**Issue by EtiamNullam** [VSCodeVim/Vim#4238]
**Describe the bug**
If lines are yanked to a named register then they will be replaced by selected text on put.

**To Reproduce**

1. Yank **line(s)** to a named register (`"ayy`, `V"ay` or `"add`).
2. Select some text using mode `VISUAL` or `VISUAL LINE` (`vw` or `V`).
3. Paste named register over the selected text (`"ap`)
4. Select different text (same as `2. step`).
5. Paste the same named register over the selected text (same as `3. step`)
6. Notice that the content of named register (in this case `a`) is now replaced with text that was selected in `3. step`

You can easily check `Vim` behavior by running a recording:

1. Copy content of this pastebin to clipboard: https://pastebin.com/f4RPceBC
2. Launch Vim.
3. Run recording by typing: `@*`

Sadly I don't think you can as easily execute record in `VSCodeVim` from clipboard, but you can follow these steps to mimic above `Vim` recording:

1. Open new file in `VSCode` with `VSCodeVim` enabled in `NORMAL` mode.
2. Type this (On `<Esc>` press the Esc key and on `<Enter>` press the Enter key):
```
ifoo<Enter>bar<Enter>333<Esc>kkV"ayjV"apjV"ap
```

**Expected behavior**
After the `3. step` named register (in the example: `a`) should still contain lines yanked in the `1. step`.

Replacing text by pasting from a named register should never replace content of this register.

Both `Vim` and (manual) `VSCodeVim` recordings should have the same result:
```
foo
foo
foo
```
but instead in `VSCodeVim` I'm getting:
```
foo
foo
bar
```

**Screenshots**
Won't help much.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: `1.11.3`
- VSCode version: `1.39.2`
- OS: `Windows 10 x64`

**Additional context**
This problem occurs only when lines are put in named register (`1. step`). For example it works as expected when words or paragraphs are put in the register even if they span across several lines) .

**Comment by J-Fields** [comment]
Should be fixed by https://github.com/VSCodeVim/Vim/pull/3891, I think

**Comment by EtiamNullam** [comment]
Sorry, I was looking for an issue and totally missed that PR.

Works as expected, thanks!

**Comment by shalen-original** [comment]
Hi there. I am still experiencing this problem, have there been issues with the linked PR?
