### ISSUE TITLE
vim not work

### ISSUE THREAD

**Issue by alanwei43** [VSCodeVim/Vim#4342]
Issue Type: <b>Bug</b>

vim not work, just like have not installed. I tried `rm -rf ~/.vscode/extensions/vscodevim.vim-1.12.0`,  reinstall extension, and restart computer, vim still not work.

Extension version: 1.12.0
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 5.0.0-36-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz (8 x 3687)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 1|
|Memory (System)|31.28GB (20.69GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|67%|
</details>

**Comment by huangzeyu** [comment]
me too, I rolled back to 1.11.3 and everything worked fine.

VS Code version: 1.40.2 f359dd69833dd8800b54d458f6d37ab7c78df520

**Comment by zires** [comment]
me too

**Comment by ldm0** [comment]
me too

**Comment by imAliAzhar** [comment]
Same here. v1.12.0 doesn't work.

**Comment by Sutherlandon** [comment]
Ditto!  Rolling back to 1.11.3 fixed the issue

**Comment by qychess** [comment]
me too

**Comment by syllr** [comment]
me too

**Comment by cetra3** [comment]
To rollback to a working version:

* Open extensions & find VIM
* Press the cog icon next to it
* Select Install Another Version
* Choose `1.11.3`
* Restart VSCODE

![vim](https://user-images.githubusercontent.com/6415435/70412341-8239b480-1aa4-11ea-88b2-50e9d85c52f2.png)

**Comment by victorqin** [comment]
me too

**Comment by branchang** [comment]
same, working on 1.11.3

**Comment by o-train** [comment]
Had to rollback too :(

**Comment by Yocss** [comment]
me too, vim V1.12.0 can't run in vscode v1.40.2 macos 10.14

**Comment by 0900304132** [comment]
same, working on 1.11.3

**Comment by chaoleili** [comment]
roll back to 1.11.3 works

**Comment by jeongwooklee** [comment]
rolled back to 1.11.3 and worked well.
(with VS code Version: `1.40.2` `f359dd69833dd8800b54d458f6d37ab7c78df520`)

**Comment by liaokaien** [comment]
same problem, rolling back do works

**Comment by astroshot** [comment]
I thought I was the only one and I rolled back too.

**Comment by Bouts2019** [comment]
me too, and used the same solution...

**Comment by fourcolors** [comment]
same here, not working.

**Comment by detailyang** [comment]
rollback works.

**Comment by longhaiqwe** [comment]
me too, vim V1.12.0 can't run in vscode v1.40.2, win10 remote to centos7.

**Comment by cookie314** [comment]
rollback works.

**Comment by DremyGit** [comment]
me too, and I can't do my work now~

**Comment by OverMighty** [comment]
Can confirm. 1.12.0 doesn't work, but rolling back to 1.11.3 works.

**Comment by zhangjinglin** [comment]
On mac 10.15.1, VSCODE 1.40.2, vim 1.12.0 doesn't work, use vim 1.11.3 works

**Comment by MondoGao** [comment]
me too

**Comment by AlseinX** [comment]
Releasing 1.12 without checking was guilty.
Programmers from all over the world stopped their work and tried to locate the problem.

**Comment by leehunkyu00** [comment]
me too,
rolling back to 1.11.3 is working

Visual Studio Code Info
Version 1.40.2
OS : Windows_NT x64 10.0.18362

**Comment by icearith** [comment]
conformed +1

**Comment by wushukai** [comment]
me too, 
remote extension did not work, rollback to 1.11.3 is working

**Comment by eisukeesaki** [comment]
**VSCodeVim v1.12.0 not working** on:

System Version: macOS 10.13.4 (17E199)
Kernel Version: Darwin 17.5.0

VSCode Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.5.0

**rolled backed to v1.11.3 and it's working.**

**Comment by magiczjp123** [comment]
same issue, rollback worked

**Comment by Hoofoo-WHU** [comment]
same, 1.12.0 not work

**Comment by chevtek** [comment]
Two words: smoke test :P

**Comment by soyarsauce** [comment]
Another report for latest version breaking on MacOS:
Extension (VsCodeVim) version: 1.12.0
VSCode version: 1.40.2
OS version: macOS 10.14.6

Current workaround:
Re-installed at version 1.11.3, disabled auto-updates in vscode so it doesn't get updated again.

**Comment by bailiyang** [comment]
so do I
i remove all my vscode and reinstall!!!
but NO effect

**Comment by shmokmt** [comment]
me too

**Comment by jkryanchou** [comment]
So Do I .

**Comment by Sh4pe** [comment]
Had the same problem, rollback worked.

**Comment by shenhe930** [comment]
me too

VsCodeVim version: 1.12.0
VSCode version: 1.40.2
OS version: macOS 10.15.1

**Comment by AlseinX** [comment]
> so do I
> i remove all my vscode and reinstall!!!
> but NO effect

I did the same rofl

**Comment by rdepke** [comment]
I have the same issue with Windows10 1903

**Comment by willzhqiang** [comment]
me too

**Comment by MetalBlueberry** [comment]
mewtwo

**Comment by numbcoder** [comment]
Almost fully feature-complete VIM integration by utilizing neovim:
https://github.com/asvetliakov/vscode-neovim

**Comment by PymZoR** [comment]
Same

**Comment by liyuanqiu** [comment]
v1.11.3 is working

How to downgrade to v1.11.3:
https://github.com/VSCodeVim/Vim/issues/4342#issuecomment-563083330

**Comment by hyUrbanManager** [comment]
me too, fuck waste my time

**Comment by TolichP** [comment]
Me too

**Comment by jay7n** [comment]
Me too. have to rollback to get it work

**Comment by londbell** [comment]
Me too.

**Comment by xujpxm** [comment]
not work +1
vscodevim version: 1.12.0
VSCode version: 1.40.2
OS version: macOS 10.12.6

Rolling back to 1.11.3 fixed also!

**Comment by Anniywell** [comment]
+1
Rollback to 1.11.3

**Comment by iyuge2** [comment]
+1
Rollback to 1.11.3
Thanks!!!

**Comment by wurikiji** [comment]
+1 
Rollback works

**Comment by ljjumper** [comment]
yeah, seems like a major problem with the new update, good to see that the rollback to 1.11.3 worked without any issue.

**Comment by robertovg** [comment]
Please update when it's fixed

**Comment by AlseinX** [comment]
> Almost fully feature-complete VIM integration by utilizing neovim:
> https://github.com/asvetliakov/vscode-neovim

I tried this, but some shitpoints that makes me never want to use it.

+ The default escape key is C-c, even though configurable. It is so rude to override widely accepted default with the author's personal preference.
+ C-c copy and C-v paste with the system clipboard not supported or need complex configuration.
+ It needs external installation and even does not autodetect the path. eg. The C# extension automatically downloads, configures and run Omnisharp as language server, and an in-box mono as its runtime, and some other extensions at least detects the path.  //By the way the XML extension by RedHat is also a shit because it needs java runtime (why do we have to configure an irrelative specific runtime just for generally used XML?) and still is the 1st place shown in the search result as the 2nd popular one for XML

**Comment by with-heart** [comment]
> * The default escape key is C-c, even though configurable. It is so rude to override widely accepted default  with the author's personal preference.

> The main reason is the `Esc` key is used in vscode to cancel/abort many things and >i just didn't have a time to test it properly
>
> I'll test and add `Esc` as second escape keybinding for next release

https://github.com/asvetliakov/vscode-neovim/issues/74

**Comment by AlseinX** [comment]
> > * The default escape key is C-c, even though configurable. It is so rude to override widely accepted default  with the author's personal preference.
> 
> > The main reason is the `Esc` key is used in vscode to cancel/abort many things and >i just didn't have a time to test it properly
> > I'll test and add `Esc` as second escape keybinding for next release
> 
> @AlseinX [asvetliakov/vscode-neovim#74](https://github.com/asvetliakov/vscode-neovim/issues/74)

What I got from this issue is

> The main reason is the Esc key is used in vscode to cancel/abort many things and i just didn't have a time to test it properly

Vscodevim has properly made it while vscode-neovim is currently unable to.
Does it mean that vscode-neovim is not mature enough for using?

**Comment by asvetliakov** [comment]
>Does it mean that vscode-neovim is not mature enough for using?

vscodevim is evolved during 3+ years and has 200+ contributors. vscode-neovim lifetime is just one month and has only single me as contributor. If you want a polished and mature vim extension continue to use VSCodeVim

**Comment by AlseinX** [comment]
It's so amazing for you to create it within just one month, integrating a vim or neovim could make it behave exactly as-is. But if he can't be installed with one click, it would be very nice.

i---Original---

**Comment by and-dutra** [comment]
The only solution to me was downgrading VsCode Vim

1. Uninstall Vim from VsCode
2. Delete the file ~/.vscode/extensions/vscodevim...
3. Disable extensions autoupdate in VsCode Settings
4. Download the VSIX file for version 1.11.3 from here https://github.com/VSCodeVim/Vim/releases
5. Install the extension in VsCode using CMD + SHIFT + P -> Install From VSIX

**Comment by alac1984** [comment]
It was just a test to see how many people are actually using the extension ;)

**Comment by webberpuma** [comment]
same problem here

**Comment by edsu** [comment]
> It was just a test to see how many people are actually using the extension ;)

Answer: lots!

**Comment by minhluuquang** [comment]
same problem

**Comment by E011011101001** [comment]
Rollback to 1.11.3 works

**Comment by rebornix** [comment]
Fixed in 1.12.1, sorry for the trouble.

**Comment by jkornblum** [comment]
1.12.1 still not working on my Mac 10.15.1 and VSCode 1.40.2
Rolling back to 1.11.x resolves issues.

**Comment by ZurrTum** [comment]
> 1.12.1 still not working on my Mac 10.15.1 and VSCode 1.40.2
> Rolling back to 1.11.x resolves issues.

me too
Activating extension `vscodevim.vim` failed:  Unable to find .vimrc file

**Comment by rebornix** [comment]
There are still issues happening, it seems related to how vsix is being unpacked. Reopen

**Comment by kenchilada** [comment]
Same problem.  Roll back fixed.

**Comment by yujincheng08** [comment]
Same here. Reinstalled previous version 1.11.3 works.

**Comment by brennongs** [comment]
rollback worked for me, before that it was like extension wasn't even installed. Need more hands or would that muck up your process?

**Comment by Dustii77** [comment]
Same issue with 1.12 not working. Rolling back gets it working again.

**Comment by E011011101001** [comment]
Ver 1.12.1 is now working fine on Mac 10.14.6 and VSCode 1.40.2.

**Comment by rebornix** [comment]
1.12.2 was out. I'll close this issue once we confirm it fixes all your problems.

There are two issues we fixed in last two minor versions

* 1.12.1. Fix the broken vsix bundle
* 1.12.2. Fix the `throw` when there is no `.vimrc` available on disk.

**Comment by dtkelch** [comment]
Confirmed that v1.12.2 works for me on MacOS 10.14.6 and 1.40.2.

**Comment by Dustii77** [comment]
1.12.2 did the trick! Thank you rebornix

**Comment by brooth** [comment]
That was pretty scary to work without vim mode. Thanks for the quick fix!

**Comment by J-Fields** [comment]
This is resolved. Thanks for being on top of it @rebornix!

**Comment by nomad-software** [comment]
What is being done to stop this happening in the future?

**Comment by chevtek** [comment]
> What is being done to stop this happening in the future?

Hopefully we at least get a refund.

**Comment by 3nuc** [comment]
> What is being done to stop this happening in the future?

I was actually thinking would it be possible to run like a headless version of VSCode in a CI pipeline that runs the built Vim extension and fails the build if the extension crashes?

**Comment by guppykang** [comment]
Somehow, this fixed all my .vimrc keybinds when I was setting up my new laptop. (at least if you're on mac)
`defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
`
