### ISSUE TITLE
Cursor position is strange after use "Go to Symbol in Editor..."

### ISSUE THREAD

**Issue by yorkz1994** [VSCodeVim/Vim#5555]
**Describe the bug**
Use "Go to Symbol in Editor..." (Ctrl + Shift +O), choose a function name for example, the cursor will jump to function definition. If now I use H key to move cursor left, the cursor will go back to the place before use "Go to Symbol in Editor...".

**To Reproduce**

1.  Press Ctrl + Shift + O to open "Go to Symbol in Editor..." panel.
2.  Choose a function name and press Enter key to go to definition.
3.  Move cursor with H or L key
4.  Cursor goes back to original place before use "Go to Symbol in Editor..."

**Expected behavior**
Cursor should be in the function definition not going back to before use H or L key.
However, J or K key works without problem.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.17.1
- VSCode version: 1.50.1
- OS: Windows 10

**Additional context**

**Comment by berknam** [comment]
@yorkz1994 Does this still happen after restarting vscode or after reloading the window?

**Comment by yorkz1994** [comment]
@berknam Yes, it is a permanent issue.

**Comment by berknam** [comment]
What I meant was for you to try closing vscode and open again, then try performing your steps to see if it still happens.

I believe this is related to the same issues that should be fixed with PR #5250.

I can't reproduce this with your steps normally. But if I manage to put vscode in the same situation as described in the mentioned issues, then this issue happens to me too. So I think this is fixed with #5250 as well.

**Comment by yorkz1994** [comment]
@berknam I have tried to close and open vscode again. The problem can reproduce no matter how many times to do closing and opening.
It seems I cannot reproduce it on ubuntu. I have 2 windows machines, both can reproduce it easily.
If you have windows 10, you can try to reproduce it.

**Comment by berknam** [comment]
I have windows 10 and I can't reproduce it, except in the situation I mentioned above. Try this:
1. Press `Ctrl+Shift+P` to open the command palette and type `vim toggle` and press `enter` to run the "Vim: Toggle Vim Mode"
2. This will disable vim
3. Now repeat step 1 to enable vim again
4. Now do your steps: press `Ctrl+Shift+o` to go to a function and press `h`

**Comment by yorkz1994** [comment]
@berknam If I do toggle vim mode, it can fix the problem sometimes. But if I tries more cursor movement, then the problem can happen again.

**Comment by berknam** [comment]
That means it probably is the same issue that has been fixed on PR #5250. Which means it should be fixed on the next version, since that PR is already merged.

**Comment by yorkz1994** [comment]
I tried another win10 (3 PCs already now), problem can be reproduced too.
Then I tried many times on Ubuntu by vnc, but I cannot reproduce it.

Problem seems Windows only.

**Comment by yorkz1994** [comment]
I downgraded to 1.16.0, problem cannot be reproduced then.

**Comment by berknam** [comment]
Like I said that should be fixed on the next version, but meanwhile if you manage to reproduce this constantly it may help figure out if there is other bugs creating the situation mentioned on that PR.

The most important thing is to try to figure out what is it that you're doing that triggers that bug. That is, after you toggle Vim and the bug goes away, have you managed to reproduce a way that makes it happen again?

Some of the cases that might trigger it are using snippets, or working with multicursors. Have you done any of this?

**Comment by JW9506** [comment]
@berknam  With [#5250 ](url), the extension now behaves more like pre 1.17.x in the userland, thanks, it should be made official asap.

**Comment by dmbfm** [comment]
This issue still happens for me in VS Code 1.53.2, on Windows 10. VsCodeVim version 1.18.9.

**Comment by billgan1024** [comment]
I am also experiencing this issue on
Version: 1.75.0
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:29:17.766Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 6.0.12-76060006-generic
Sandboxed: No

**Comment by hongwen000** [comment]
This problem is so serious. I am suffering a lot here.

**Comment by hongwen000** [comment]
> I downgraded to 1.16.0, problem cannot be reproduced then.

Thanks the God, downgrading to 1.16.0 works for me now.

**Comment by andragan** [comment]
This issue still happens for me in VS Code 1.76.2, on macOS Ventura 13.2.1. VsCodeVim version 1.25.2.
downgrading to VsCodeVim version 1.16.0 fixes it

**Comment by teddyknox** [comment]
Crazy that this is still broken. Can't wait until we have AI to fix bugs like these.

**Comment by hongwen000** [comment]
Can confirm this still happen + 1

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Ahmad D. Y. ***@***.***>
发送时间: 2023年9月21日 0:03
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [VSCodeVim/Vim] Cursor position is strange after use "Go to Symbol in Editor..." (#5555)


can confirm this still happen

fix: use vscode-neovim instead of this extension 💀

**Comment by ArkFreestyle** [comment]
Also facing this issue on VSCode version 1.82.2, VSCodeVim version 1.26.0

After goto symbol, the cursor position does not update to the newly navigated symbol. The page navigates yes, but as soon as j or k is pressed, you're back to where your cursor was previously.

**Comment by xaljer** [comment]
Not only the "Go to Symbol in Editor...", other goto action like previous/next changes have the same problem. Key board work flow is badly affected by this issue.
