### ISSUE TITLE
Surrogate pairs (emojis, etc.) are not handled well in insert mode

### ISSUE THREAD

**Issue by athos** [VSCodeVim/Vim#6046]
**Description**

When I'm typing in a text containing [surrogate pairs](https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Surrogates) (like emoji, relatively complicated kanji, etc.) using my [input method](https://en.wikipedia.org/wiki/Input_method) in the insert mode, the text gets garbled as shown in the GIF below:

<img src="https://user-images.githubusercontent.com/27441/105862486-29740500-6033-11eb-96af-184a846a3795.gif" width="382">

After digging into the codebase, I found that [this line of code](https://github.com/VSCodeVim/Vim/blob/7f8da746873e51070a211f6fa22496b0ff399e60/src/actions/commands/insert.ts#L306) does not seem to handle surrogate pairs well:

```javascript
    const char = this.keysPressed[this.keysPressed.length - 1];
```

This can be confirmed as follows:

```javascript
> var text = '🤔'
> text.length
2
> text[text.length-1]
'�'
> var text2 = '𩸽'
> text2.length
2
> text2[text2.length-1]
'�'
```

To fix this behavior, I think we need to do something like what VSCode does in [getPrevCodePoint](https://github.com/microsoft/vscode/blob/578e2dc4ee7f2f508be6910c99af3f9ab866dab0/src/vs/base/common/strings.ts#L468-L477). If we had it, we should be able to handle text containing surrogate pairs well like the following:

```javascript
> String.fromCodePoint(getPrevCodePoint(text, text.length))
'🤔'
```

**To Reproduce**
Typing in a text containing surrogate pairs in the insert mode.

**Expected behavior**
Expected characters are successfully entered in the editor.

**Environment:**
- Extension (VsCodeVim) version: 1.18.5
- VSCode version: 1.52.1
- OS: macOS Big Sur (Darwin x64 20.2.0)

**Comment by xiekeyi98** [comment]
I have the same issue.

Would you mind taking a look @J-Fields   , thanks.

**Comment by J-Fields** [comment]
Can you confirm this is still an issue? This implementation was changed a bit in 1.19.0

**Comment by athos** [comment]
Thank you for letting me know! 🤝

I've checked with 1.19.2, but I still see the same issue, unfortunately.

**Comment by midorizemi** [comment]
Hello. I still have same issue too.
![f87bd71cca6c1ab1f885630eade49358](https://user-images.githubusercontent.com/927671/116652506-44eb0500-a9c0-11eb-833c-a4a9f3df833a.gif)

However, I found that I can get around this problem by using [:emojisense:](https://github.com/mattbierner/vscode-emojisense) . Please refer to it.


Environment:
- Windows 10 Pro, Ver.: 2004, (build: 19041.928)
- VSCode Ver.: 1.55.2
- VSCodeVim Ver.: 1.20.2

Thank you.

**Comment by athos** [comment]
Yeah, I know that extension exists. Moreover, VS Code itself has built-in support for emoji input (`Ctrl-Cmd-Space` on Mac), which works fine in the insert mode of VSCodeVim.

But, this issue is not only about emoji, but also about any other characters that are represented as surrogate pairs, so it needs to be resolved, even then.

**Comment by uiii** [comment]
This happens to me, when I try to insert emoji using `Windows + .`. It prints the emoji for a short moment and then changes to two question marks. It is very annoying because now I have to type in some other editor and then paste it to vscode.

**Comment by HouCoder** [comment]
Spend an hour on this issue, finally realized it's vscodevim's issue for not having emojis properly displayed.

**Comment by athos** [comment]
Wow, I've confirmed that the latest release resolves the issue. Excellent! 🎉 🎉
Thank you so much from the bottom of my heart for tackling this longstanding issue!

**Comment by dubaaron** [comment]
Hi, according to above, this was fixed, but I am experiencing this problem now on Mac, vscodevim version 1.24.3, VSCode version: 1.68.1 ... in insert mode, if I try to trigger the emoji insertion dialog (Ctrl + Cmd + Space), nothing happens.

I can trigger it in another app, and then paste into insert mode in vscode vim, but can't seen to trigger it in vscode itself now. 😥

PS -- this is very cool extension, thanks for making this.  Now I can improve my vim skills while using VSCode, haha 😁

**Comment by k1832** [comment]
The insert mode fix from PR #7977 is still working. #9929 extends surrogate pair handling to normal mode commands (`a`, `r`, `s`, `~`, `ga`) that were still broken, and adds regression tests to prevent future breakage.
