### ISSUE TITLE
Cursor jumps to the beginning of the file after switching from another one

### ISSUE THREAD

**Issue by rivaldi8** [VSCodeVim/Vim#8200]
**Describe the bug**
Sometimes, after switching from one file to another (through tabs), pressing a key makes the cursor jump to the beginning of the file.

**To Reproduce**
I haven't found yet what's triggering the issue. However, once it happens, it can be reproduced like this:

1.  One a file editor, move away from the beginning of the file (row 0, column 0, if you are there), either with the keyboard or with the mouse. For example, press 'j' to move down one line.
2.  Switch to another file tab with the keyboard or mouse.
3.  Switch back to the previous file.
4.  Pressing any key (Esc included) but modifiers (Ctrl, Alt...) jumps to the beginning.
5. Closing and reopening the file fixes it.

**Expected behavior**
The cursor should remain in the same position.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.24.3
- VSCode version: 1.74.2
- OS: Linux

**Additional context**
This issue appeared after the upgrade to VS Code 1.74, so it may be related to #8157, although a file affected by the former might not be by the latter.

**Comment by Vanaldito** [comment]
I have the same problem and I found a way to reproduce it.

In a file with enough lines (in my case 80 are enough). If you go to the last line and start going up by holding k to the first line. Then, when changing to another file and returning to the original, the problem will happen.

Sometimes it is necessary to repeat the process again to cause the bug.

@rivaldi8, could you confirm if the same thing happens to you?

**Comment by rivaldi8** [comment]
@Vanaldito I confirm I can reproduce following your steps. Although it doesn't happens always, it does frequently enough.

It seem something related with the scrolling and hitting the bottom of the file. Sometimes, just hitting the bottom triggers the issue. I also found it doesn't always jump to the first line. Sometimes it goes to the second or third instead.

Strangely in my other computer, with similar settings and extensions, I can't seem to reproduce any of these bugs. I have to investigate if there's some setting that's causing it.

By the way, I just checked with VS Code 1.74.3 and the bug is still there.

**Comment by nviennot** [comment]
Same. It's awful.

**Comment by pixeldin** [comment]
Any ideas or progress? looking forward to solving:)

**Comment by basepi** [comment]
I'm was newly hitting this as of today. I think I updated to 1.75 yesterday, but I'm not sure from which version. For me it was happening 100% of the time when switching tabs between files.

I started poking around, and disabling [`vim-leave-insertmode`](https://marketplace.visualstudio.com/items?itemName=xavbergeron.vim-leave-insertmode) has fixed this issue for me, at least for now. Re-enabling that extension immediately brings the problem back. 🤷‍♂️

Hopefully this is a useful datapoint.

**Comment by theorlangur** [comment]
In my case it's really simple to reproduce:
being in one file, perform GoToDefinition that would bring you to another file
go back to the previous one ('Alt+LeftArrow')
the position is correct at first, but trying to navigate with hjkl jumps to the beginning of the file

no additional vim-related extensions are involved, no insert mode, all in normal

VSCode: 1.76.0
VsCodeVim: 1.25.2

**Comment by Nauxscript** [comment]
I got the same problems for months...

reproduce step: 
1. Open two files.
2. Scroll down in one file (in most cases this file may be have hundreds of line of code).
3. Switch to the other file, then back to the original file.
4. Pressing arrow keys to move the cursor
5. Cursor will jump to the top of the file.

my environment:
Extension (VsCodeVim) version: 1.25.2
VSCode version: 1.76.0
OS: macOS 13.1

its really annoying me 😢

**Comment by RoXuS** [comment]
Reload Window command seems to solve the issue for a moment then it come back after a while moment

**Comment by Nauxscript** [comment]
> Reload Window command seems to solve the issue for a moment then it come back after a while moment

yes, I haven't found a solution for now, every time i open vsc and feel it becomes normal, the problem comes back again...

**Comment by navarrothiago** [comment]
I have the same problem on Linux, Vscode v1.75, VSCodeVim v1.25.2, Go v0.38.0. The workaround I followed this https://github.com/VSCodeVim/Vim/issues/3444#issuecomment-460095886: install an old version for while (1.0.2).

**Comment by iluuu1994** [comment]
I mostly experienced this for `gd` and then going back with `C-o`. I replaced these actions with the native VSCode actions. It's not been long enough to verify that this solved the issue fully but it looks promising so far.

**keybindings.json**

```json
[
    {
        "key": "ctrl+o",
        "command": "workbench.action.navigateBack",
        "when": "canNavigateBack",
    },
    {
        "key": "ctrl+i",
        "command": "workbench.action.navigateForward",
        "when": "canNavigateForward",
    },
    {
        "key": "ctrl+i",
        "command": "-editor.action.triggerSuggest",
    },
]
```

**settings.json**

```json
{
    "vim.handleKeys": {
        "<C-o>": false,
        "<C-i>": false,
    },
    "vim.normalModeKeyBindings": [ 
        {
            "before": ["g", "p"],
            "commands": ["editor.action.peekDefinition"],
        },
        {
            "before": ["g", "d"],
            "commands": ["editor.action.revealDefinition"],
        },
    ],
}
```

**Comment by atulpatildbz** [comment]
For some reason, I only experience this issue when I switch from a file where I’m in visual mode. I was able to fix it by adding "after": ["<Esc>"], to tab switch commands

```
    {
      "before": ["g", "t"],
      "after": ["<Esc>"],
      "commands": ["workbench.action.nextEditor"]
    },
```

https://github.com/atulpatildbz/dotFiles/blob/92271f16a8772237a2ebbcc72b2fd0f1e40f3a18/vscode/settings.json#L226

**Comment by iluuu1994** [comment]
Right! I experience this when highlighting a word, pressing Ctrl+T to jump to that symbol (clangd chokes on some files in our codebase so that `gd` doesn't work) and then going back with Ctrl+O.

**Comment by fafrd** [comment]
I can confirm that @atulpatildbz's `g` `t` -> `"workbench.action.nextEditor"` solution works around the issue. Haven't had it since

**Comment by lucidBrot** [comment]
> However, it doesn't have to be visual mode for the problem to occur. The problem will occur as long as there is any sort of selected text in the current buffer  

I am having the same issue **without** any text selected, and in **normal** mode. All I need to do to reproduce is, for example:  

1.  `G` to jump to the end of file
2.  `gt` to go to the next file tab
3. `gT` to go back to the previous tab
4. Notice the cursor jumped back to the start of the file

It also happens if I enter insert mode after step 1 and use the mouse to go to the other tab (step 2). Or when I use the mouse in steps 2 *and* 3.  

In fact, it even happens when I use the mouse for all the steps - no keyboard used.

If I disable vscodevim and reload, it does not happen. Obviously I can only test it with the mouse there. If I re-enable vscodevim, even without a reload, it happens again. Doing then a reload also does not fix it (just to be sure).

#### VScode Version
```
Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

#### vscodevim Version
`v1.25.2`

**Comment by lawrence-laz** [comment]
I cannot get the work around working with `<C-Tab>` and `<C-S-Tab>`

I tried this:
```json
// settings.json
"vim.handleKeys": {
     "<C-Tab>": true,
     "<C-S-Tab>": true,
},
"vim.visualModeKeyBindingsNonRecursive": [
    { "before": [ "<C-Tab>" ], "after": [ "<Esc>" ], "commands": [ "workbench.action.nextEditor" ] },
    { "before": [ "<C-S-Tab>" ], "after": [ "<Esc>" ], "commands": [ "workbench.action.previousEditor" ] },
]
```
But it seems that `<C-Tab>` cannot be mapped from settings.json? Because the action is not trigerred.

Then I tried this:
```json
// keybindings.json
{ "key": "ctrl+tab", "command": "vim.remap", "args": { "command": "workbench.action.nextEditor", "after": [ "<Esc>"  ] } },
```
But I think we cannot mix `command` and `after` in `args`? Because only `<Esc>` is triggered, the editor does not change.

Then I tried this in multiple ways:
```json
// keybindings.json
    { "key": "ctrl+tab", "command": "vim.remap", "args": { "after": [ "<Esc>", ":vsc workbench.action.nextEditor", "<CR>" ] } },
    { "key": "ctrl+shift+tab", "command": "vim.remap", "args": { "after": [ "<Esc>", ":", "v", "s", "c", " ", "w", "o", "r", "k", "b", "e", "n", "c", "h", ".", "a", "c", "t", "i", "o", "n", ".", "p", "r", "e", "v", "i", "o", "u", "s", "E", "d", "i", "t", "<CR>" ] } },
```
And neither trigger the action of switching the editor.

The regular VSCode mapping does switch editors, but I cannot add the workaround of `<Esc>` as an after action.

Any ideas?

**Comment by Nauxscript** [comment]
hey guys, I noticed that this problem has not reappeared in the past month or so... but I dont know why 😂
my current environment:

VScode:
Version: 1.78.0
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:15:29.774Z (5 days ago)
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No

OS: MacOS Ventura 13.1

**Comment by Miklak93** [comment]
For me, downgrading the version to v1.24.3 did the job.

**Comment by magniff** [comment]
I've switched from vim to vscode specifically because of that extension. Looks like it's time to go back, as the current state of the extension is a deal breaker for me.

**Comment by magniff** [comment]
Ok, looks like i've found a workaround: https://github.com/VSCodeVim/Vim/pull/8426.

**Comment by magniff** [comment]
Can anyone confirm the fix worked? ^

**Comment by lucidBrot** [comment]
@magniff I can confirm:  

* using the `master` branch but built using <kbd>F5</kbd> I could still reproduce the bug easily and consistently
* using the `cursor_pesky_jumps` branch the bug seems to be fixed!

I hope this gets merged soon. Thank you already for the fix

**Comment by magniff** [comment]
So, looks like we have a solution, that's a bummer the team is not merging it.

**Comment by aethnemitchell** [comment]
Still having this problem as described. Bumping for merge.

**Comment by TomMalitz** [comment]
Any update on this? Would like to see that fix merged.

**Comment by magniff** [comment]
VsCode `1.80.1`, VIM extension: `1.25.2`: cant reproduce anymore. The bug origin seem to fixed in vscode itself.

**Comment by cyxr001** [comment]
Have any update ?
I use VsCode 1.80.2, VIM extension: 1.25.2.
The problem is still exist

**Comment by tengwu** [comment]
> For me, downgrading the version to v1.24.3 did the job.

Great job, it works for me well!

**Comment by iosifzota** [comment]
Hello. I've found a workaround: reload window.

The command is "Developer: Reload Window".

**Comment by skplunkerin** [comment]
> Hello. I've found another simple workaround: reload window.

Same, my workflow is:

1. eventually the bug starts
2. I reload the window
3. the bug is temporarily fixed
4. rinse-and-repeat-all-day

**Comment by powellnorma** [comment]
The recently merged fix seems to work for me, one can install current master like this:

```sh
npm install -g @vscode/vsce yarn gulp-cli

git clone https://github.com/VSCodeVim/Vim
cd Vim
yarn install
vsce package
code --install-extension vim-1.25.2.vsix
```

**Comment by navarrothiago** [comment]
I am still facing the same issue.

Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:25.257Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.1.55-1-MANJARO
VSCodeVim: v1.26.1
