### ISSUE TITLE
File is edited with random edits when pressing k

### ISSUE THREAD

**Issue by iosifzota** [VSCodeVim/Vim#9322]
**Describe the bug**
File is edited randomnly when pressing k.

**To Reproduce**

1.  Open any file
2.  Navigate through the file as usual (j, k) (normal mode of course)
3. Press k (at some moment ... it's random)

**Expected behavior**
The cursor moves up and down in the file and the file contents remain intact.

**Screenshots**
![image](https://github.com/user-attachments/assets/177cae66-e136-44bb-acae-ce999ab9ff19)

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: v1.28.1 (latest at this point)
- VSCode version: 1.94.2
- OS: Windows_NT x64 10.0.19045

**Comment by nexdep** [comment]
experiencing the same. I am with:
- windows 11
- VS code insiders
- Extension VSCodeVim

All at the latest version. DId you manage to fix the issue? Thanks

**Comment by grax8225x** [comment]
Same.
When you press and hold the K button in an empty text file, it will look like the image below.
It looks very strange, as if the Vim extension's processing can't keep up.

![Screenshot from 2024-11-26 18-14-17](https://github.com/user-attachments/assets/d2649035-f493-4ded-b39d-28af0e372bdf)

**Comment by forfrt** [comment]
Got the same problem, very confusing

**Comment by nexdep** [comment]
it is fixed for me with the latest vs code insiders update

**Comment by grax8225x** [comment]
I am also using the Insider version, and it seems the issue has been fixed.
But I’m not sure which version the issue was fixed in.

Version: 1.96.0-insider
Commit: 138f619c86f1199955d53b4166bef66ef252935c

**Comment by h-jennings** [comment]
I'm still having this issue even when using VSCode insiders 😞. The issue tends to be worse in larger files I've found. Though I'm still able to reproduce with a blank text file. Usually only happens hold down a key for more than a few lines.

https://github.com/user-attachments/assets/9da3dd67-9045-4cc5-9031-56f51e0a89cc


Version: 1.96.0-insider
Commit: 138f619c86f1199955d53b4166bef66ef252935c

**Comment by iosifzota** [comment]
VSCode November release just arrived, I'll see if the issue is still there. Personally I cannot use VSCode insiders, for me VSCode already forces me to use the Reload Window command from time to time, I don't want to risk more instability.

**Comment by iosifzota** [comment]
It still doesn't work after the VSCode update. It was fine for a couple of hours but then it happened again.

Version: 1.96.0 (user setup)
Date: 2024-12-11T02:29:09.626Z
OS: Windows_NT x64 10.0.19045

Vim extension version: 1.29.0

**Comment by ovidiu-eremia** [comment]
I happens for me also on Windows WSL, with:
```
lsb_release -a         
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
```
```
code-insiders --version
1.97.0-insider
1db1071148a1efa3b7ad7592d64507ef52536a3e
x64
```
```
vscodevim.vim
Version
1.29.0
```

Here is a recording of replicating the bug:

https://github.com/user-attachments/assets/68009f5a-7f60-452f-b746-24c3632f8fd7

In this recording I am just using j, w, and k, and the problem happens when I keep pressing k.

And here is the log for it:
[2025-01-15 115355.329 [info] vscodevim_logs.txt](https://github.com/user-attachments/files/18422110/2025-01-15.115355.329.info.vscodevim_logs.txt)

Thank you!

**Comment by LucasAschenbach** [comment]
I'm facing the same issue for various keys but mostly "k" when pressing the key on repeat.

**Potential Fix:** On my system, I have decreased the key-repeat time from the default 30ms to only 15ms. When I revert back to 30ms the issue disappears. However, I have had this configuration for quite some time but the issue only started appearing in the last few months.

Version: 1.97.0-insider
Commit: 3d0aeb47a2ecfde9ff5141470b30c36d41c321d9
Date: 2025-01-20T05:04:25.114Z
Electron: 32.2.7
ElectronBuildId: 10660205
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.2.0

**Comment by h-jennings** [comment]
> I'm facing the same issue for various keys but mostly "k" when pressing the key on repeat.
> 
> **Potential Hint at Fix:** On my system, I have decreased the key-repeat time from the default 30ms to only 15ms. When I revert back to 30ms the issue disappears. However, I have had this configuration for quite some time but the issue only started appearing in the last few months.
> 
> Version: 1.97.0-insider Commit: 3d0aeb47a2ecfde9ff5141470b30c36d41c321d9 Date: 2025-01-20T05:04:25.114Z Electron: 32.2.7 ElectronBuildId: 10660205 Chromium: 128.0.6613.186 Node.js: 20.18.1 V8: 12.8.374.38-electron.0 OS: Darwin arm64 24.2.0

It's a bit unfortunate, but after I reverted my key repeat settings, the issue largely disappeared. Like Lucas, I previously had no problems with a faster key repeat. It seems to be an issue on the VSCode side, as other Vim plugins are experiencing the same problem. I tried VSCode Neovim, and the issue was just as bad, if not worse.

<img width="479" alt="Image" src="https://github.com/user-attachments/assets/8963636c-88dd-4da4-9a84-1e745621e1db" />

**Comment by grax8225x** [comment]
> I am also using the Insider version, and it seems the issue has been fixed. But I’m not sure which version the issue was fixed in.
> 
> Version: 1.96.0-insider Commit: 138f619c86f1199955d53b4166bef66ef252935c

I thought it was fixed, but the same issue has occurred again.
I don’t know where it’s coming from.
Version: 1.97.0-insider
Commit: d9069970f94c133d4bb5d300e9f8d7f174843cd9

**Comment by nexdep** [comment]
the issue is coming and going, all the solutions (vscode update, keyboard tweaks, etc) worked for a bit until they didn't. I switched to the neovim extension and the problem is not arising so i might do the jump

**Comment by grax8225x** [comment]
I tried Neovim extensions as well, but they didn’t work for me.
